In [ ]:
import json

def transform_table(table):
    id = table['id']
    title = id.split('_')[0].lower().replace('_', ' ')
    cells = []

    # Flatten column headers
    flat_headers = []
    for header in table['column_header']:
        flat_headers.extend(header)

    # Add column headers as cells
    for col_idx, header in enumerate(flat_headers):
        cells.append({
            "text": f"{header} |",
            "row_idx": 0,
            "col_idx": col_idx
        })

    # Add row headers as a new column and data cells
    for row_idx, (row_header, row_data) in enumerate(zip(table['row_header'], table['data']), start=1):
        # Add row header as the first column
        if row_header:
            cells.append({
                "text": f"{' '.join(row_header)} |",
                "row_idx": row_idx,
                "col_idx": 0
            })

        # Add data cells
        for col_idx, cell_data in enumerate(row_data, start=len(row_header)):
            cells.append({
                "text": f"{cell_data} |",
                "row_idx": row_idx,
                "col_idx": col_idx
            })

    # Remove the trailing '|' from the last cell in each row
    for cell in cells:
        if cell['col_idx'] == len(flat_headers) - 1:
            cell['text'] = cell['text'].rstrip('| ') + '.'

    return {
        "id": f"{title}_{id}",
        "title": title,
        "cells": cells
    }

# Read the JSONL file and transform each table
transformed_tables = []
with open('/content/aitqa_tables.jsonl', 'r') as file:
    for line in file:
        table = json.loads(line)
        transformed_table = transform_table(table)
        transformed_tables.append(transformed_table)

# Write the transformed tables to a new JSONL file
with open('transformed_tables.jsonl', 'w') as file:
    for table in transformed_tables:
        json.dump(table, file)
        file.write('\n')

In [ ]:
import pandas as pd
import json

json_list = []
with open('/content/transformed_tables.jsonl', 'r') as file:
    for line in file:
        json_list.append(json.loads(line))

json_list

[{'id': 'tab-0_tab-0',
  'title': 'tab-0',
  'cells': [{'text': 'Year |', 'row_idx': 0, 'col_idx': 0},
   {'text': 'Gallons Consumed (in millions) |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Fuel Expense       (in millions) |', 'row_idx': 0, 'col_idx': 2},
   {'text': 'Average Price Per Gallon |', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Percentage of Total Operating Expense |',
    'row_idx': 0,
    'col_idx': 4},
   {'text': 'Available Seat Miles per Fuel Gallon.',
    'row_idx': 0,
    'col_idx': 5}]},
 {'id': 'tab-1_tab-1',
  'title': 'tab-1',
  'cells': [{'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 0},
   {'text': '2018 |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 2},
   {'text': '2017 (a) |', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 4},
   {'text': '2016 (a) |', 'row_idx': 0, 'col_idx': 5},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 6},
   {'text': '2015 |', 'row_idx': 0, 'col_idx': 7},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 8},
   {'text': '2014.', 'row_idx': 0, 'col_idx': 9},
   {'text': 'Consolidated (b) Passengers (thousands) (c) |',
    'row_idx': 1,
    'col_idx': 0},
   {'text': '158,330 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '148,067 |', 'row_idx': 1, 'col_idx': 3},
   {'text': '143,177 |', 'row_idx': 1, 'col_idx': 4},
   {'text': '140,369 |', 'row_idx': 1, 'col_idx': 5},
   {'text': '138,029 |', 'row_idx': 1, 'col_idx': 6},
   {'text': 'Consolidated (b) Revenue passenger miles ("RPMs") (millions) (d) |',
    'row_idx': 2,
    'col_idx': 0},
   {'text': '230,155 |', 'row_idx': 2, 'col_idx': 2},
   {'text': '216,261 |', 'row_idx': 2, 'col_idx': 3},
   {'text': '210,309 |', 'row_idx': 2, 'col_idx': 4},
   {'text': '208,611 |', 'row_idx': 2, 'col_idx': 5},
   {'text': '205,559 |', 'row_idx': 2, 'col_idx': 6},
   {'text': 'Consolidated (b) Available seat miles ("ASMs") (millions) (e) |',
    'row_idx': 3,
    'col_idx': 0},
   {'text': '275,262 |', 'row_idx': 3, 'col_idx': 2},
   {'text': '262,386 |', 'row_idx': 3, 'col_idx': 3},
   {'text': '253,590 |', 'row_idx': 3, 'col_idx': 4},
   {'text': '250,003 |', 'row_idx': 3, 'col_idx': 5},
   {'text': '246,021 |', 'row_idx': 3, 'col_idx': 6},
   {'text': 'Consolidated (b) Cargo revenue ton miles (millions) (f) |',
    'row_idx': 4,
    'col_idx': 0},
   {'text': '3,425 |', 'row_idx': 4, 'col_idx': 2},
   {'text': '3,316 |', 'row_idx': 4, 'col_idx': 3},
   {'text': '2,805 |', 'row_idx': 4, 'col_idx': 4},
   {'text': '2,614 |', 'row_idx': 4, 'col_idx': 5},
   {'text': '2,487 |', 'row_idx': 4, 'col_idx': 6},
   {'text': 'Consolidated (b) Passenger load factor (g) |',
    'row_idx': 5,
    'col_idx': 0},
   {'text': '83.6% |', 'row_idx': 5, 'col_idx': 2},
   {'text': '82.4% |', 'row_idx': 5, 'col_idx': 3},
   {'text': '82.9% |', 'row_idx': 5, 'col_idx': 4},
   {'text': '83.4% |', 'row_idx': 5, 'col_idx': 5},
   {'text': '83.6% |', 'row_idx': 5, 'col_idx': 6},
   {'text': 'Consolidated (b) Passenger revenue per available seat mile ("PRASM") (cents) |',
    'row_idx': 6,
    'col_idx': 0},
   {'text': '13.70 |', 'row_idx': 6, 'col_idx': 2},
   {'text': '13.13 |', 'row_idx': 6, 'col_idx': 3},
   {'text': '13.18 |', 'row_idx': 6, 'col_idx': 4},
   {'text': '13.11 |', 'row_idx': 6, 'col_idx': 5},
   {'text': '13.72 |', 'row_idx': 6, 'col_idx': 6},
   {'text': 'Consolidated (b) Total revenue per available seat mile ("TRASM") (cents) |',
    'row_idx': 7,
    'col_idx': 0},
   {'text': '15.00 |', 'row_idx': 7, 'col_idx': 2},
   {'text': '14.40 |', 'row_idx': 7, 'col_idx': 3},
   {'text': '14.42 |', 'row_idx': 7, 'col_idx': 4},
   {'text': '15.15 |', 'row_idx': 7, 'col_idx': 5},
   {'text': '15.81 |', 'row_idx': 7, 'col_idx': 6},
   {'text': 'Consolidated (b) Average yield per revenue passenger mile ("Yield") (cents) (h) |',
    'row_idx': 8,
    'col_idx': 0},
   {'text': '16.38 |', 'row_idx': 8, 'col_idx': 2},
   {'text': '15.93 |', 'row_idx': 8, 'col_idx': 3},
   {'text': '15.90 |', 'row_idx': 8, 'col_idx': 4},
   {'text': '15.72 |', 'row_idx': 8, 'col_idx': 5},
   {'text': '16.42 |', 'row_idx': 8, 'col_idx': 6},
   {'text': 'Consolidated (b) Cost per available seat mile ("CASM") (cents) |',
    'row_idx': 9,
    'col_idx': 0},
   {'text': '13.81 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '13.00 |', 'row_idx': 9, 'col_idx': 3},
   {'text': '12.70 |', 'row_idx': 9, 'col_idx': 4},
   {'text': '13.08 |', 'row_idx': 9, 'col_idx': 5},
   {'text': '14.85 |', 'row_idx': 9, 'col_idx': 6},
   {'text': 'Consolidated (b) Average price per gallon of fuel, including fuel taxes |',
    'row_idx': 10,
    'col_idx': 0},
   {'text': '$2.25 |', 'row_idx': 10, 'col_idx': 2},
   {'text': '$1.74 |', 'row_idx': 10, 'col_idx': 3},
   {'text': '$1.49 |', 'row_idx': 10, 'col_idx': 4},
   {'text': '$1.94 |', 'row_idx': 10, 'col_idx': 5},
   {'text': '$2.99 |', 'row_idx': 10, 'col_idx': 6},
   {'text': 'Consolidated (b) Fuel gallons consumed (millions) |',
    'row_idx': 11,
    'col_idx': 0},
   {'text': '4,137 |', 'row_idx': 11, 'col_idx': 2},
   {'text': '3,978 |', 'row_idx': 11, 'col_idx': 3},
   {'text': '3,904 |', 'row_idx': 11, 'col_idx': 4},
   {'text': '3,886 |', 'row_idx': 11, 'col_idx': 5},
   {'text': '3,905 |', 'row_idx': 11, 'col_idx': 6},
   {'text': 'Consolidated (b) Average stage length (miles) (i) |',
    'row_idx': 12,
    'col_idx': 0},
   {'text': '1,446 |', 'row_idx': 12, 'col_idx': 2},
   {'text': '1,460 |', 'row_idx': 12, 'col_idx': 3},
   {'text': '1,473 |', 'row_idx': 12, 'col_idx': 4},
   {'text': '1,487 |', 'row_idx': 12, 'col_idx': 5},
   {'text': '1,480 |', 'row_idx': 12, 'col_idx': 6},
   {'text': 'Consolidated (b) Average daily utilization of each mainline aircraft (hours:minutes) (j) |',
    'row_idx': 13,
    'col_idx': 0},
   {'text': '10:45 |', 'row_idx': 13, 'col_idx': 2},
   {'text': '10:27 |', 'row_idx': 13, 'col_idx': 3},
   {'text': '10:06 |', 'row_idx': 13, 'col_idx': 4},
   {'text': '10:24 |', 'row_idx': 13, 'col_idx': 5},
   {'text': '10:26 |', 'row_idx': 13, 'col_idx': 6}]},
 {'id': 'tab-2_tab-2',
  'title': 'tab-2',
  'cells': [{'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 0},
   {'text': 'Domestic |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 2},
   {'text': 'Atlantic |', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 4},
   {'text': 'Pacific |', 'row_idx': 0, 'col_idx': 5},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 6},
   {'text': 'Latin |', 'row_idx': 0, 'col_idx': 7},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 8},
   {'text': 'Total |', 'row_idx': 0, 'col_idx': 9},
   {'text': ' |', 'row_idx': 0, 'col_idx': 10},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 11},
   {'text': ' |', 'row_idx': 0, 'col_idx': 12},
   {'text': 'Domestic |', 'row_idx': 0, 'col_idx': 13},
   {'text': 'Atlantic.', 'row_idx': 0, 'col_idx': 14},
   {'text': 'Passenger revenue (in millions) |', 'row_idx': 1, 'col_idx': 0},
   {'text': '$2,340 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$688 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$185 |', 'row_idx': 1, 'col_idx': 3},
   {'text': '$33 |', 'row_idx': 1, 'col_idx': 4},
   {'text': '$3,246 |', 'row_idx': 1, 'col_idx': 5},
   {'text': ' |', 'row_idx': 1, 'col_idx': 6},
   {'text': 'Passenger revenue |', 'row_idx': 2, 'col_idx': 0},
   {'text': '11.1% |', 'row_idx': 2, 'col_idx': 1},
   {'text': '11.7 % |', 'row_idx': 2, 'col_idx': 2},
   {'text': '4.3 % |', 'row_idx': 2, 'col_idx': 3},
   {'text': '1.0 % |', 'row_idx': 2, 'col_idx': 4},
   {'text': '9.4% |', 'row_idx': 2, 'col_idx': 5},
   {'text': ' |', 'row_idx': 2, 'col_idx': 6},
   {'text': 'Average fare per passenger |', 'row_idx': 3, 'col_idx': 0},
   {'text': '2.8% |', 'row_idx': 3, 'col_idx': 1},
   {'text': '0.2 % |', 'row_idx': 3, 'col_idx': 2},
   {'text': '8.5 % |', 'row_idx': 3, 'col_idx': 3},
   {'text': '2.5 % |', 'row_idx': 3, 'col_idx': 4},
   {'text': '2.3% |', 'row_idx': 3, 'col_idx': 5},
   {'text': ' |', 'row_idx': 3, 'col_idx': 6},
   {'text': 'Yield |', 'row_idx': 4, 'col_idx': 0},
   {'text': '3.8% |', 'row_idx': 4, 'col_idx': 1},
   {'text': '(0.4)% |', 'row_idx': 4, 'col_idx': 2},
   {'text': '2.7 % |', 'row_idx': 4, 'col_idx': 3},
   {'text': '(0.3)% |', 'row_idx': 4, 'col_idx': 4},
   {'text': '2.8% |', 'row_idx': 4, 'col_idx': 5},
   {'text': ' |', 'row_idx': 4, 'col_idx': 6},
   {'text': 'PRASM |', 'row_idx': 5, 'col_idx': 0},
   {'text': '4.1% |', 'row_idx': 5, 'col_idx': 1},
   {'text': '6.3 % |', 'row_idx': 5, 'col_idx': 2},
   {'text': '3.0 % |', 'row_idx': 5, 'col_idx': 3},
   {'text': '0.8 % |', 'row_idx': 5, 'col_idx': 4},
   {'text': '4.3% |', 'row_idx': 5, 'col_idx': 5},
   {'text': ' |', 'row_idx': 5, 'col_idx': 6},
   {'text': 'Passengers |', 'row_idx': 6, 'col_idx': 0},
   {'text': '8.1% |', 'row_idx': 6, 'col_idx': 1},
   {'text': '11.5 % |', 'row_idx': 6, 'col_idx': 2},
   {'text': '(3.9)% |', 'row_idx': 6, 'col_idx': 3},
   {'text': '(1.4)% |', 'row_idx': 6, 'col_idx': 4},
   {'text': '6.9% |', 'row_idx': 6, 'col_idx': 5},
   {'text': ' |', 'row_idx': 6, 'col_idx': 6},
   {'text': 'RPMs (traffic) |', 'row_idx': 7, 'col_idx': 0},
   {'text': '7.0% |', 'row_idx': 7, 'col_idx': 1},
   {'text': '12.1 % |', 'row_idx': 7, 'col_idx': 2},
   {'text': '1.5 % |', 'row_idx': 7, 'col_idx': 3},
   {'text': '1.3 % |', 'row_idx': 7, 'col_idx': 4},
   {'text': '6.4% |', 'row_idx': 7, 'col_idx': 5},
   {'text': ' |', 'row_idx': 7, 'col_idx': 6},
   {'text': 'ASMs (capacity) |', 'row_idx': 8, 'col_idx': 0},
   {'text': '6.7% |', 'row_idx': 8, 'col_idx': 1},
   {'text': '5.1 % |', 'row_idx': 8, 'col_idx': 2},
   {'text': '1.3 % |', 'row_idx': 8, 'col_idx': 3},
   {'text': '0.3 % |', 'row_idx': 8, 'col_idx': 4},
   {'text': '4.9% |', 'row_idx': 8, 'col_idx': 5},
   {'text': ' |', 'row_idx': 8, 'col_idx': 6},
   {'text': 'Passenger load factor (points) |', 'row_idx': 9, 'col_idx': 0},
   {'text': '0.2 |', 'row_idx': 9, 'col_idx': 1},
   {'text': '5.1 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '0.2 |', 'row_idx': 9, 'col_idx': 3},
   {'text': '0.8 |', 'row_idx': 9, 'col_idx': 4},
   {'text': '1.2 |', 'row_idx': 9, 'col_idx': 5},
   {'text': ' |', 'row_idx': 9, 'col_idx': 6},
   {'text': '11 |', 'row_idx': 10, 'col_idx': 0},
   {'text': ' |', 'row_idx': 10, 'col_idx': 1},
   {'text': ' |', 'row_idx': 10, 'col_idx': 2},
   {'text': ' |', 'row_idx': 10, 'col_idx': 3},
   {'text': ' |', 'row_idx': 10, 'col_idx': 4},
   {'text': ' |', 'row_idx': 10, 'col_idx': 5},
   {'text': '(a) See Part II, Item 6, Selected Financial Data, of this report for the definition of these statistics. |',
    'row_idx': 10,
    'col_idx': 6}]},
 {'id': 'tab-3_tab-3',
  'title': 'tab-3',
  'cells': [{'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 0},
   {'text': 'Domestic |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 2},
   {'text': 'Atlantic |', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 4},
   {'text': 'Pacific |', 'row_idx': 0, 'col_idx': 5},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 6},
   {'text': 'Latin |', 'row_idx': 0, 'col_idx': 7},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 8},
   {'text': 'Total |', 'row_idx': 0, 'col_idx': 9},
   {'text': ' |', 'row_idx': 0, 'col_idx': 10},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 11},
   {'text': ' |', 'row_idx': 0, 'col_idx': 12},
   {'text': 'Domestic |', 'row_idx': 0, 'col_idx': 13},
   {'text': 'Atlantic |', 'row_idx': 0, 'col_idx': 14},
   {'text': 'Pacific |', 'row_idx': 0, 'col_idx': 15},
   {'text': 'Latin |', 'row_idx': 0, 'col_idx': 16},
   {'text': 'Total.', 'row_idx': 0, 'col_idx': 17},
   {'text': 'Passenger revenue (in millions) |', 'row_idx': 1, 'col_idx': 0},
   {'text': '$885 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$117 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$(144) |', 'row_idx': 1, 'col_idx': 3},
   {'text': '$173 |', 'row_idx': 1, 'col_idx': 4},
   {'text': '$1,031 |', 'row_idx': 1, 'col_idx': 5},
   {'text': ' |', 'row_idx': 1, 'col_idx': 6},
   {'text': 'Passenger revenue |', 'row_idx': 2, 'col_idx': 0},
   {'text': '4.4 % |', 'row_idx': 2, 'col_idx': 1},
   {'text': '2.0% |', 'row_idx': 2, 'col_idx': 2},
   {'text': '(3.2)% |', 'row_idx': 2, 'col_idx': 3},
   {'text': '5.8% |', 'row_idx': 2, 'col_idx': 4},
   {'text': '3.1 % |', 'row_idx': 2, 'col_idx': 5},
   {'text': ' |', 'row_idx': 2, 'col_idx': 6},
   {'text': 'Average fare per passenger |', 'row_idx': 3, 'col_idx': 0},
   {'text': '0.2 % |', 'row_idx': 3, 'col_idx': 1},
   {'text': '1.5% |', 'row_idx': 3, 'col_idx': 2},
   {'text': '(0.1)% |', 'row_idx': 3, 'col_idx': 3},
   {'text': '4.0% |', 'row_idx': 3, 'col_idx': 4},
   {'text': '(0.3)% |', 'row_idx': 3, 'col_idx': 5},
   {'text': ' |', 'row_idx': 3, 'col_idx': 6},
   {'text': 'Yield |', 'row_idx': 4, 'col_idx': 0},
   {'text': '(0.3)% |', 'row_idx': 4, 'col_idx': 1},
   {'text': '1.1% |', 'row_idx': 4, 'col_idx': 2},
   {'text': '(2.4)% |', 'row_idx': 4, 'col_idx': 3},
   {'text': '4.1% |', 'row_idx': 4, 'col_idx': 4},
   {'text': '0.2 % |', 'row_idx': 4, 'col_idx': 5},
   {'text': ' |', 'row_idx': 4, 'col_idx': 6},
   {'text': 'PRASM |', 'row_idx': 5, 'col_idx': 0},
   {'text': '(0.5)% |', 'row_idx': 5, 'col_idx': 1},
   {'text': '1.6% |', 'row_idx': 5, 'col_idx': 2},
   {'text': '(6.0)% |', 'row_idx': 5, 'col_idx': 3},
   {'text': '3.3% |', 'row_idx': 5, 'col_idx': 4},
   {'text': '(0.4)% |', 'row_idx': 5, 'col_idx': 5},
   {'text': ' |', 'row_idx': 5, 'col_idx': 6},
   {'text': 'Passengers |', 'row_idx': 6, 'col_idx': 0},
   {'text': '4.2 % |', 'row_idx': 6, 'col_idx': 1},
   {'text': '0.5% |', 'row_idx': 6, 'col_idx': 2},
   {'text': '(3.1)% |', 'row_idx': 6, 'col_idx': 3},
   {'text': '1.7% |', 'row_idx': 6, 'col_idx': 4},
   {'text': '3.4 % |', 'row_idx': 6, 'col_idx': 5},
   {'text': ' |', 'row_idx': 6, 'col_idx': 6},
   {'text': 'RPMs (traffic) |', 'row_idx': 7, 'col_idx': 0},
   {'text': '4.7 % |', 'row_idx': 7, 'col_idx': 1},
   {'text': '0.9% |', 'row_idx': 7, 'col_idx': 2},
   {'text': '(0.9)% |', 'row_idx': 7, 'col_idx': 3},
   {'text': '1.6% |', 'row_idx': 7, 'col_idx': 4},
   {'text': '2.8 % |', 'row_idx': 7, 'col_idx': 5},
   {'text': ' |', 'row_idx': 7, 'col_idx': 6},
   {'text': 'ASMs (capacity) |', 'row_idx': 8, 'col_idx': 0},
   {'text': '4.9 % |', 'row_idx': 8, 'col_idx': 1},
   {'text': '0.4% |', 'row_idx': 8, 'col_idx': 2},
   {'text': '2.9 % |', 'row_idx': 8, 'col_idx': 3},
   {'text': '2.4% |', 'row_idx': 8, 'col_idx': 4},
   {'text': '3.5 % |', 'row_idx': 8, 'col_idx': 5},
   {'text': ' |', 'row_idx': 8, 'col_idx': 6},
   {'text': 'Passenger load factor (points) |', 'row_idx': 9, 'col_idx': 0},
   {'text': '(0.2) |', 'row_idx': 9, 'col_idx': 1},
   {'text': '0.4 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '(3.0) |', 'row_idx': 9, 'col_idx': 3},
   {'text': '(0.7) |', 'row_idx': 9, 'col_idx': 4},
   {'text': '(0.5) |', 'row_idx': 9, 'col_idx': 5},
   {'text': ' |', 'row_idx': 9, 'col_idx': 6},
   {'text': '11 |', 'row_idx': 10, 'col_idx': 0},
   {'text': ' |', 'row_idx': 10, 'col_idx': 1},
   {'text': ' |', 'row_idx': 10, 'col_idx': 2},
   {'text': ' |', 'row_idx': 10, 'col_idx': 3},
   {'text': ' |', 'row_idx': 10, 'col_idx': 4},
   {'text': ' |', 'row_idx': 10, 'col_idx': 5},
   {'text': '(a) See Part II, Item 6, Selected Financial Data, of this report for the definition of these statistics. |',
    'row_idx': 10,
    'col_idx': 6}]},
 {'id': 'tab-4_tab-4',
  'title': 'tab-4',
  'cells': [{'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 0},
   {'text': '2018 |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 2},
   {'text': '2017 (a) |', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 4},
   {'text': '2016 (a).', 'row_idx': 0, 'col_idx': 5},
   {'text': 'Operating revenue: Passenger revenue |',
    'row_idx': 1,
    'col_idx': 0},
   {'text': '$37,706 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$34,460 |', 'row_idx': 1, 'col_idx': 3},
   {'text': '$33,429 |', 'row_idx': 1, 'col_idx': 4},
   {'text': 'Operating revenue: Cargo |', 'row_idx': 2, 'col_idx': 0},
   {'text': '1,237 |', 'row_idx': 2, 'col_idx': 2},
   {'text': '1,114 |', 'row_idx': 2, 'col_idx': 3},
   {'text': '934 |', 'row_idx': 2, 'col_idx': 4},
   {'text': 'Operating revenue: Other operating revenue |',
    'row_idx': 3,
    'col_idx': 0},
   {'text': '2,360 |', 'row_idx': 3, 'col_idx': 2},
   {'text': '2,210 |', 'row_idx': 3, 'col_idx': 3},
   {'text': '2,195 |', 'row_idx': 3, 'col_idx': 4},
   {'text': 'Operating revenue: Total operating revenue |',
    'row_idx': 4,
    'col_idx': 0},
   {'text': '41,303 |', 'row_idx': 4, 'col_idx': 2},
   {'text': '37,784 |', 'row_idx': 4, 'col_idx': 3},
   {'text': '36,558 |', 'row_idx': 4, 'col_idx': 4},
   {'text': 'Operating expense: Salaries and related costs |',
    'row_idx': 5,
    'col_idx': 0},
   {'text': '11,458 |', 'row_idx': 5, 'col_idx': 2},
   {'text': '10,941 |', 'row_idx': 5, 'col_idx': 3},
   {'text': '10,176 |', 'row_idx': 5, 'col_idx': 4},
   {'text': 'Operating expense: Aircraft fuel |', 'row_idx': 6, 'col_idx': 0},
   {'text': '9,307 |', 'row_idx': 6, 'col_idx': 2},
   {'text': '6,913 |', 'row_idx': 6, 'col_idx': 3},
   {'text': '5,813 |', 'row_idx': 6, 'col_idx': 4},
   {'text': 'Operating expense: Regional capacity purchase |',
    'row_idx': 7,
    'col_idx': 0},
   {'text': '2,601 |', 'row_idx': 7, 'col_idx': 2},
   {'text': '2,232 |', 'row_idx': 7, 'col_idx': 3},
   {'text': '2,197 |', 'row_idx': 7, 'col_idx': 4},
   {'text': 'Operating expense: Landing fees and other rent |',
    'row_idx': 8,
    'col_idx': 0},
   {'text': '2,359 |', 'row_idx': 8, 'col_idx': 2},
   {'text': '2,240 |', 'row_idx': 8, 'col_idx': 3},
   {'text': '2,165 |', 'row_idx': 8, 'col_idx': 4},
   {'text': 'Operating expense: Depreciation and amortization |',
    'row_idx': 9,
    'col_idx': 0},
   {'text': '2,240 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '2,149 |', 'row_idx': 9, 'col_idx': 3},
   {'text': '1,977 |', 'row_idx': 9, 'col_idx': 4},
   {'text': 'Operating expense: Aircraft maintenance materials and outside repairs |',
    'row_idx': 10,
    'col_idx': 0},
   {'text': '1,767 |', 'row_idx': 10, 'col_idx': 2},
   {'text': '1,856 |', 'row_idx': 10, 'col_idx': 3},
   {'text': '1,749 |', 'row_idx': 10, 'col_idx': 4},
   {'text': 'Operating expense: Distribution expenses |',
    'row_idx': 11,
    'col_idx': 0},
   {'text': '1,558 |', 'row_idx': 11, 'col_idx': 2},
   {'text': '1,435 |', 'row_idx': 11, 'col_idx': 3},
   {'text': '1,395 |', 'row_idx': 11, 'col_idx': 4},
   {'text': 'Operating expense: Aircraft rent |', 'row_idx': 12, 'col_idx': 0},
   {'text': '433 |', 'row_idx': 12, 'col_idx': 2},
   {'text': '621 |', 'row_idx': 12, 'col_idx': 3},
   {'text': '680 |', 'row_idx': 12, 'col_idx': 4},
   {'text': 'Operating expense: Special charges |',
    'row_idx': 13,
    'col_idx': 0},
   {'text': '487 |', 'row_idx': 13, 'col_idx': 2},
   {'text': '176 |', 'row_idx': 13, 'col_idx': 3},
   {'text': '745 |', 'row_idx': 13, 'col_idx': 4},
   {'text': 'Operating expense: Other operating expenses |',
    'row_idx': 14,
    'col_idx': 0},
   {'text': '5,801 |', 'row_idx': 14, 'col_idx': 2},
   {'text': '5,550 |', 'row_idx': 14, 'col_idx': 3},
   {'text': '5,317 |', 'row_idx': 14, 'col_idx': 4},

tentativo 2

In [ ]:
import json

def transform_table(table):
    id = table['id']
    title = id.split('_')[0].lower().replace('_', ' ')
    cells = []

    # Flatten column headers
    flat_headers = []
    for header in table['column_header']:
        flat_headers.extend(header)

    # Add column headers as cells
    for col_idx, header in enumerate(flat_headers):
        cells.append({
            "text": f"{header} |",
            "row_idx": 0,
            "col_idx": col_idx
        })

    # Add data cells
    for row_idx, row_data in enumerate(table['data'], start=1):
        # Add data cells
        for col_idx, cell_data in enumerate(row_data):
            cells.append({
                "text": f"{cell_data} |",
                "row_idx": row_idx,
                "col_idx": col_idx
            })

    # Remove the trailing '|' from the last cell in each row
    for cell in cells:
        if cell['col_idx'] == len(flat_headers) - 1:
            cell['text'] = cell['text'].rstrip('| ') + '.'

    return {
        "id": f"{title}_{id}",
        "title": title,
        "cells": cells
    }

# Read the JSONL file and transform each table
transformed_tables = []
with open('/content/aitqa_tables.jsonl', 'r') as file:
    for line in file:
        table = json.loads(line)
        transformed_table = transform_table(table)
        transformed_tables.append(transformed_table)

# Write the transformed tables to a new JSONL file
with open('transformed_tables2.jsonl', 'w') as file:
    for table in transformed_tables:
        json.dump(table, file)
        file.write('\n')

In [ ]:
import pandas as pd
import json

json_list = []
with open('/content/transformed_tables2.jsonl', 'r') as file:
    for line in file:
        json_list.append(json.loads(line))

json_list

[{'id': 'tab-0_tab-0',
  'title': 'tab-0',
  'cells': [{'text': 'Year |', 'row_idx': 0, 'col_idx': 0},
   {'text': 'Gallons Consumed (in millions) |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Fuel Expense       (in millions) |', 'row_idx': 0, 'col_idx': 2},
   {'text': 'Average Price Per Gallon |', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Percentage of Total Operating Expense |',
    'row_idx': 0,
    'col_idx': 4},
   {'text': 'Available Seat Miles per Fuel Gallon.',
    'row_idx': 0,
    'col_idx': 5},
   {'text': '2018 |', 'row_idx': 1, 'col_idx': 0},
   {'text': '4,137 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$9,307 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$2.25 |', 'row_idx': 1, 'col_idx': 3},
   {'text': '24% |', 'row_idx': 1, 'col_idx': 4},
   {'text': '67.', 'row_idx': 1, 'col_idx': 5},
   {'text': '2017 |', 'row_idx': 2, 'col_idx': 0},
   {'text': '3,978 |', 'row_idx': 2, 'col_idx': 1},
   {'text': '$6,913 |', 'row_idx': 2, 'col_idx': 2},
   {'text': '$1.74 |', 'row_idx': 2, 'col_idx': 3},
   {'text': '20% |', 'row_idx': 2, 'col_idx': 4},
   {'text': '66.', 'row_idx': 2, 'col_idx': 5},
   {'text': '2016 |', 'row_idx': 3, 'col_idx': 0},
   {'text': '3,904 |', 'row_idx': 3, 'col_idx': 1},
   {'text': '$5,813 |', 'row_idx': 3, 'col_idx': 2},
   {'text': '$1.49 |', 'row_idx': 3, 'col_idx': 3},
   {'text': '18% |', 'row_idx': 3, 'col_idx': 4},
   {'text': '65.', 'row_idx': 3, 'col_idx': 5}]},
 {'id': 'tab-1_tab-1',
  'title': 'tab-1',
  'cells': [{'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 0},
   {'text': '2018 |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 2},
   {'text': '2017 (a) |', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 4},
   {'text': '2016 (a) |', 'row_idx': 0, 'col_idx': 5},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 6},
   {'text': '2015 |', 'row_idx': 0, 'col_idx': 7},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 8},
   {'text': '2014.', 'row_idx': 0, 'col_idx': 9},
   {'text': '158,330 |', 'row_idx': 1, 'col_idx': 0},
   {'text': '148,067 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '143,177 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '140,369 |', 'row_idx': 1, 'col_idx': 3},
   {'text': '138,029 |', 'row_idx': 1, 'col_idx': 4},
   {'text': '230,155 |', 'row_idx': 2, 'col_idx': 0},
   {'text': '216,261 |', 'row_idx': 2, 'col_idx': 1},
   {'text': '210,309 |', 'row_idx': 2, 'col_idx': 2},
   {'text': '208,611 |', 'row_idx': 2, 'col_idx': 3},
   {'text': '205,559 |', 'row_idx': 2, 'col_idx': 4},
   {'text': '275,262 |', 'row_idx': 3, 'col_idx': 0},
   {'text': '262,386 |', 'row_idx': 3, 'col_idx': 1},
   {'text': '253,590 |', 'row_idx': 3, 'col_idx': 2},
   {'text': '250,003 |', 'row_idx': 3, 'col_idx': 3},
   {'text': '246,021 |', 'row_idx': 3, 'col_idx': 4},
   {'text': '3,425 |', 'row_idx': 4, 'col_idx': 0},
   {'text': '3,316 |', 'row_idx': 4, 'col_idx': 1},
   {'text': '2,805 |', 'row_idx': 4, 'col_idx': 2},
   {'text': '2,614 |', 'row_idx': 4, 'col_idx': 3},
   {'text': '2,487 |', 'row_idx': 4, 'col_idx': 4},
   {'text': '83.6% |', 'row_idx': 5, 'col_idx': 0},
   {'text': '82.4% |', 'row_idx': 5, 'col_idx': 1},
   {'text': '82.9% |', 'row_idx': 5, 'col_idx': 2},
   {'text': '83.4% |', 'row_idx': 5, 'col_idx': 3},
   {'text': '83.6% |', 'row_idx': 5, 'col_idx': 4},
   {'text': '13.70 |', 'row_idx': 6, 'col_idx': 0},
   {'text': '13.13 |', 'row_idx': 6, 'col_idx': 1},
   {'text': '13.18 |', 'row_idx': 6, 'col_idx': 2},
   {'text': '13.11 |', 'row_idx': 6, 'col_idx': 3},
   {'text': '13.72 |', 'row_idx': 6, 'col_idx': 4},
   {'text': '15.00 |', 'row_idx': 7, 'col_idx': 0},
   {'text': '14.40 |', 'row_idx': 7, 'col_idx': 1},
   {'text': '14.42 |', 'row_idx': 7, 'col_idx': 2},
   {'text': '15.15 |', 'row_idx': 7, 'col_idx': 3},
   {'text': '15.81 |', 'row_idx': 7, 'col_idx': 4},
   {'text': '16.38 |', 'row_idx': 8, 'col_idx': 0},
   {'text': '15.93 |', 'row_idx': 8, 'col_idx': 1},
   {'text': '15.90 |', 'row_idx': 8, 'col_idx': 2},
   {'text': '15.72 |', 'row_idx': 8, 'col_idx': 3},
   {'text': '16.42 |', 'row_idx': 8, 'col_idx': 4},
   {'text': '13.81 |', 'row_idx': 9, 'col_idx': 0},
   {'text': '13.00 |', 'row_idx': 9, 'col_idx': 1},
   {'text': '12.70 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '13.08 |', 'row_idx': 9, 'col_idx': 3},
   {'text': '14.85 |', 'row_idx': 9, 'col_idx': 4},
   {'text': '$2.25 |', 'row_idx': 10, 'col_idx': 0},
   {'text': '$1.74 |', 'row_idx': 10, 'col_idx': 1},
   {'text': '$1.49 |', 'row_idx': 10, 'col_idx': 2},
   {'text': '$1.94 |', 'row_idx': 10, 'col_idx': 3},
   {'text': '$2.99 |', 'row_idx': 10, 'col_idx': 4},
   {'text': '4,137 |', 'row_idx': 11, 'col_idx': 0},
   {'text': '3,978 |', 'row_idx': 11, 'col_idx': 1},
   {'text': '3,904 |', 'row_idx': 11, 'col_idx': 2},
   {'text': '3,886 |', 'row_idx': 11, 'col_idx': 3},
   {'text': '3,905 |', 'row_idx': 11, 'col_idx': 4},
   {'text': '1,446 |', 'row_idx': 12, 'col_idx': 0},
   {'text': '1,460 |', 'row_idx': 12, 'col_idx': 1},
   {'text': '1,473 |', 'row_idx': 12, 'col_idx': 2},
   {'text': '1,487 |', 'row_idx': 12, 'col_idx': 3},
   {'text': '1,480 |', 'row_idx': 12, 'col_idx': 4},
   {'text': '10:45 |', 'row_idx': 13, 'col_idx': 0},
   {'text': '10:27 |', 'row_idx': 13, 'col_idx': 1},
   {'text': '10:06 |', 'row_idx': 13, 'col_idx': 2},
   {'text': '10:24 |', 'row_idx': 13, 'col_idx': 3},
   {'text': '10:26 |', 'row_idx': 13, 'col_idx': 4}]},
 {'id': 'tab-2_tab-2',
  'title': 'tab-2',
  'cells': [{'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 0},
   {'text': 'Domestic |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 2},
   {'text': 'Atlantic |', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 4},
   {'text': 'Pacific |', 'row_idx': 0, 'col_idx': 5},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 6},
   {'text': 'Latin |', 'row_idx': 0, 'col_idx': 7},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 8},
   {'text': 'Total |', 'row_idx': 0, 'col_idx': 9},
   {'text': ' |', 'row_idx': 0, 'col_idx': 10},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 11},
   {'text': ' |', 'row_idx': 0, 'col_idx': 12},
   {'text': 'Domestic |', 'row_idx': 0, 'col_idx': 13},
   {'text': 'Atlantic.', 'row_idx': 0, 'col_idx': 14},
   {'text': '$2,340 |', 'row_idx': 1, 'col_idx': 0},
   {'text': '$688 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$185 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$33 |', 'row_idx': 1, 'col_idx': 3},
   {'text': '$3,246 |', 'row_idx': 1, 'col_idx': 4},
   {'text': ' |', 'row_idx': 1, 'col_idx': 5},
   {'text': '11.1% |', 'row_idx': 2, 'col_idx': 0},
   {'text': '11.7 % |', 'row_idx': 2, 'col_idx': 1},
   {'text': '4.3 % |', 'row_idx': 2, 'col_idx': 2},
   {'text': '1.0 % |', 'row_idx': 2, 'col_idx': 3},
   {'text': '9.4% |', 'row_idx': 2, 'col_idx': 4},
   {'text': ' |', 'row_idx': 2, 'col_idx': 5},
   {'text': '2.8% |', 'row_idx': 3, 'col_idx': 0},
   {'text': '0.2 % |', 'row_idx': 3, 'col_idx': 1},
   {'text': '8.5 % |', 'row_idx': 3, 'col_idx': 2},
   {'text': '2.5 % |', 'row_idx': 3, 'col_idx': 3},
   {'text': '2.3% |', 'row_idx': 3, 'col_idx': 4},
   {'text': ' |', 'row_idx': 3, 'col_idx': 5},
   {'text': '3.8% |', 'row_idx': 4, 'col_idx': 0},
   {'text': '(0.4)% |', 'row_idx': 4, 'col_idx': 1},
   {'text': '2.7 % |', 'row_idx': 4, 'col_idx': 2},
   {'text': '(0.3)% |', 'row_idx': 4, 'col_idx': 3},
   {'text': '2.8% |', 'row_idx': 4, 'col_idx': 4},
   {'text': ' |', 'row_idx': 4, 'col_idx': 5},
   {'text': '4.1% |', 'row_idx': 5, 'col_idx': 0},
   {'text': '6.3 % |', 'row_idx': 5, 'col_idx': 1},
   {'text': '3.0 % |', 'row_idx': 5, 'col_idx': 2},
   {'text': '0.8 % |', 'row_idx': 5, 'col_idx': 3},
   {'text': '4.3% |', 'row_idx': 5, 'col_idx': 4},
   {'text': ' |', 'row_idx': 5, 'col_idx': 5},
   {'text': '8.1% |', 'row_idx': 6, 'col_idx': 0},
   {'text': '11.5 % |', 'row_idx': 6, 'col_idx': 1},
   {'text': '(3.9)% |', 'row_idx': 6, 'col_idx': 2},
   {'text': '(1.4)% |', 'row_idx': 6, 'col_idx': 3},
   {'text': '6.9% |', 'row_idx': 6, 'col_idx': 4},
   {'text': ' |', 'row_idx': 6, 'col_idx': 5},
   {'text': '7.0% |', 'row_idx': 7, 'col_idx': 0},
   {'text': '12.1 % |', 'row_idx': 7, 'col_idx': 1},
   {'text': '1.5 % |', 'row_idx': 7, 'col_idx': 2},
   {'text': '1.3 % |', 'row_idx': 7, 'col_idx': 3},
   {'text': '6.4% |', 'row_idx': 7, 'col_idx': 4},
   {'text': ' |', 'row_idx': 7, 'col_idx': 5},
   {'text': '6.7% |', 'row_idx': 8, 'col_idx': 0},
   {'text': '5.1 % |', 'row_idx': 8, 'col_idx': 1},
   {'text': '1.3 % |', 'row_idx': 8, 'col_idx': 2},
   {'text': '0.3 % |', 'row_idx': 8, 'col_idx': 3},
   {'text': '4.9% |', 'row_idx': 8, 'col_idx': 4},
   {'text': ' |', 'row_idx': 8, 'col_idx': 5},
   {'text': '0.2 |', 'row_idx': 9, 'col_idx': 0},
   {'text': '5.1 |', 'row_idx': 9, 'col_idx': 1},
   {'text': '0.2 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '0.8 |', 'row_idx': 9, 'col_idx': 3},
   {'text': '1.2 |', 'row_idx': 9, 'col_idx': 4},
   {'text': ' |', 'row_idx': 9, 'col_idx': 5},
   {'text': ' |', 'row_idx': 10, 'col_idx': 0},
   {'text': ' |', 'row_idx': 10, 'col_idx': 1},
   {'text': ' |', 'row_idx': 10, 'col_idx': 2},
   {'text': ' |', 'row_idx': 10, 'col_idx': 3},
   {'text': ' |', 'row_idx': 10, 'col_idx': 4},
   {'text': '(a) See Part II, Item 6, Selected Financial Data, of this report for the definition of these statistics. |',
    'row_idx': 10,
    'col_idx': 5}]},
 {'id': 'tab-3_tab-3',
  'title': 'tab-3',
  'cells': [{'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 0},
   {'text': 'Domestic |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 2},
   {'text': 'Atlantic |', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 4},
   {'text': 'Pacific |', 'row_idx': 0, 'col_idx': 5},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 6},
   {'text': 'Latin |', 'row_idx': 0, 'col_idx': 7},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 8},
   {'text': 'Total |', 'row_idx': 0, 'col_idx': 9},
   {'text': ' |', 'row_idx': 0, 'col_idx': 10},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 11},
   {'text': ' |', 'row_idx': 0, 'col_idx': 12},
   {'text': 'Domestic |', 'row_idx': 0, 'col_idx': 13},
   {'text': 'Atlantic |', 'row_idx': 0, 'col_idx': 14},
   {'text': 'Pacific |', 'row_idx': 0, 'col_idx': 15},
   {'text': 'Latin |', 'row_idx': 0, 'col_idx': 16},
   {'text': 'Total.', 'row_idx': 0, 'col_idx': 17},
   {'text': '$885 |', 'row_idx': 1, 'col_idx': 0},
   {'text': '$117 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$(144) |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$173 |', 'row_idx': 1, 'col_idx': 3},
   {'text': '$1,031 |', 'row_idx': 1, 'col_idx': 4},
   {'text': ' |', 'row_idx': 1, 'col_idx': 5},
   {'text': '4.4 % |', 'row_idx': 2, 'col_idx': 0},
   {'text': '2.0% |', 'row_idx': 2, 'col_idx': 1},
   {'text': '(3.2)% |', 'row_idx': 2, 'col_idx': 2},
   {'text': '5.8% |', 'row_idx': 2, 'col_idx': 3},
   {'text': '3.1 % |', 'row_idx': 2, 'col_idx': 4},
   {'text': ' |', 'row_idx': 2, 'col_idx': 5},
   {'text': '0.2 % |', 'row_idx': 3, 'col_idx': 0},
   {'text': '1.5% |', 'row_idx': 3, 'col_idx': 1},
   {'text': '(0.1)% |', 'row_idx': 3, 'col_idx': 2},
   {'text': '4.0% |', 'row_idx': 3, 'col_idx': 3},
   {'text': '(0.3)% |', 'row_idx': 3, 'col_idx': 4},
   {'text': ' |', 'row_idx': 3, 'col_idx': 5},
   {'text': '(0.3)% |', 'row_idx': 4, 'col_idx': 0},
   {'text': '1.1% |', 'row_idx': 4, 'col_idx': 1},
   {'text': '(2.4)% |', 'row_idx': 4, 'col_idx': 2},
   {'text': '4.1% |', 'row_idx': 4, 'col_idx': 3},
   {'text': '0.2 % |', 'row_idx': 4, 'col_idx': 4},
   {'text': ' |', 'row_idx': 4, 'col_idx': 5},
   {'text': '(0.5)% |', 'row_idx': 5, 'col_idx': 0},
   {'text': '1.6% |', 'row_idx': 5, 'col_idx': 1},
   {'text': '(6.0)% |', 'row_idx': 5, 'col_idx': 2},
   {'text': '3.3% |', 'row_idx': 5, 'col_idx': 3},
   {'text': '(0.4)% |', 'row_idx': 5, 'col_idx': 4},
   {'text': ' |', 'row_idx': 5, 'col_idx': 5},
   {'text': '4.2 % |', 'row_idx': 6, 'col_idx': 0},
   {'text': '0.5% |', 'row_idx': 6, 'col_idx': 1},
   {'text': '(3.1)% |', 'row_idx': 6, 'col_idx': 2},
   {'text': '1.7% |', 'row_idx': 6, 'col_idx': 3},
   {'text': '3.4 % |', 'row_idx': 6, 'col_idx': 4},
   {'text': ' |', 'row_idx': 6, 'col_idx': 5},
   {'text': '4.7 % |', 'row_idx': 7, 'col_idx': 0},
   {'text': '0.9% |', 'row_idx': 7, 'col_idx': 1},
   {'text': '(0.9)% |', 'row_idx': 7, 'col_idx': 2},
   {'text': '1.6% |', 'row_idx': 7, 'col_idx': 3},
   {'text': '2.8 % |', 'row_idx': 7, 'col_idx': 4},
   {'text': ' |', 'row_idx': 7, 'col_idx': 5},
   {'text': '4.9 % |', 'row_idx': 8, 'col_idx': 0},
   {'text': '0.4% |', 'row_idx': 8, 'col_idx': 1},
   {'text': '2.9 % |', 'row_idx': 8, 'col_idx': 2},
   {'text': '2.4% |', 'row_idx': 8, 'col_idx': 3},
   {'text': '3.5 % |', 'row_idx': 8, 'col_idx': 4},
   {'text': ' |', 'row_idx': 8, 'col_idx': 5},
   {'text': '(0.2) |', 'row_idx': 9, 'col_idx': 0},
   {'text': '0.4 |', 'row_idx': 9, 'col_idx': 1},
   {'text': '(3.0) |', 'row_idx': 9, 'col_idx': 2},
   {'text': '(0.7) |', 'row_idx': 9, 'col_idx': 3},
   {'text': '(0.5) |', 'row_idx': 9, 'col_idx': 4},
   {'text': ' |', 'row_idx': 9, 'col_idx': 5},
   {'text': ' |', 'row_idx': 10, 'col_idx': 0},
   {'text': ' |', 'row_idx': 10, 'col_idx': 1},
   {'text': ' |', 'row_idx': 10, 'col_idx': 2},
   {'text': ' |', 'row_idx': 10, 'col_idx': 3},
   {'text': ' |', 'row_idx': 10, 'col_idx': 4},
   {'text': '(a) See Part II, Item 6, Selected Financial Data, of this report for the definition of these statistics. |',
    'row_idx': 10,
    'col_idx': 5}]},
 {'id': 'tab-4_tab-4',
  'title': 'tab-4',
  'cells': [{'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 0},
   {'text': '2018 |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 2},
   {'text': '2017 (a) |', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 4},
   {'text': '2016 (a).', 'row_idx': 0, 'col_idx': 5},
   {'text': '$37,706 |', 'row_idx': 1, 'col_idx': 0},
   {'text': '$34,460 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$33,429 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '1,237 |', 'row_idx': 2, 'col_idx': 0},
   {'text': '1,114 |', 'row_idx': 2, 'col_idx': 1},
   {'text': '934 |', 'row_idx': 2, 'col_idx': 2},
   {'text': '2,360 |', 'row_idx': 3, 'col_idx': 0},
   {'text': '2,210 |', 'row_idx': 3, 'col_idx': 1},
   {'text': '2,195 |', 'row_idx': 3, 'col_idx': 2},
   {'text': '41,303 |', 'row_idx': 4, 'col_idx': 0},
   {'text': '37,784 |', 'row_idx': 4, 'col_idx': 1},
   {'text': '36,558 |', 'row_idx': 4, 'col_idx': 2},
   {'text': '11,458 |', 'row_idx': 5, 'col_idx': 0},
   {'text': '10,941 |', 'row_idx': 5, 'col_idx': 1},
   {'text': '10,176 |', 'row_idx': 5, 'col_idx': 2},
   {'text': '9,307 |', 'row_idx': 6, 'col_idx': 0},
   {'text': '6,913 |', 'row_idx': 6, 'col_idx': 1},
   {'text': '5,813 |', 'row_idx': 6, 'col_idx': 2},
   {'text': '2,601 |', 'row_idx': 7, 'col_idx': 0},
   {'text': '2,232 |', 'row_idx': 7, 'col_idx': 1},
   {'text': '2,197 |', 'row_idx': 7, 'col_idx': 2},
   {'text': '2,359 |', 'row_idx': 8, 'col_idx': 0},
   {'text': '2,240 |', 'row_idx': 8, 'col_idx': 1},
   {'text': '2,165 |', 'row_idx': 8, 'col_idx': 2},
   {'text': '2,240 |', 'row_idx': 9, 'col_idx': 0},
   {'text': '2,149 |', 'row_idx': 9, 'col_idx': 1},
   {'text': '1,977 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '1,767 |', 'row_idx': 10, 'col_idx': 0},
   {'text': '1,856 |', 'row_idx': 10, 'col_idx': 1},
   {'text': '1,749 |', 'row_idx': 10, 'col_idx': 2},
   {'text': '1,558 |', 'row_idx': 11, 'col_idx': 0},
   {'text': '1,435 |', 'row_idx': 11, 'col_idx': 1},
   {'text': '1,395 |', 'row_idx': 11, 'col_idx': 2},
   {'text': '433 |', 'row_idx': 12, 'col_idx': 0},
   {'text': '621 |', 'row_idx': 12, 'col_idx': 1},
   {'text': '680 |', 'row_idx': 12, 'col_idx': 2},
   {'text': '487 |', 'row_idx': 13, 'col_idx': 0},
   {'text': '176 |', 'row_idx': 13, 'col_idx': 1},
   {'text': '745 |', 'row_idx': 13, 'col_idx': 2},
   {'text': '5,801 |', 'row_idx': 14, 'col_idx': 0},
   {'text': '5,550 |', 'row_idx': 14, 'col_idx': 1},
   {'text': '5,317 |', 'row_idx': 14, 'col_idx': 2},
   {'text': '38,011 |', 'row_idx': 15, 'col_idx': 0},
   {'text': '34,113 |', 'row_idx': 15, 'col_idx': 1},
   {'text': '32,214 |', 'row_idx': 15, 'col_idx': 2},
   {'text': '3,292 |', 'row_idx': 16, 'col_idx': 0},
   {'text': '3,671 |', 'row_idx': 16, 'col_idx': 1},
   {'text': '4,344 |', 'row_idx': 16, 'col_idx': 2},
   {'text': '(729) |', 'row_idx': 17, 'col_idx': 0},
   {'text': '(671) |', 'row_idx': 17, 'col_idx': 1},
   {'text': '(674) |', 'row_idx': 17, 'col_idx': 2},
   {'text': '70 |', 'row_idx': 18, 'col_idx': 0},
   {'text': '84 |', 'row_idx': 18, 'col_idx': 1},
   {'text': '72 |', 'row_idx': 18, 'col_idx': 2},
   {'text': '101 |', 'row_idx': 19, 'col_idx': 0},
   {'text': '57 |', 'row_idx': 19, 'col_idx': 1},
   {'text': '42 |', 'row_idx': 19, 'col_idx': 2},
   {'text': '(76) |', 'row_idx': 20, 'col_idx': 0},
   {'text': '(101) |', 'row_idx': 20, 'col_idx': 1},
   {'text': '(11) |', 'row_idx': 20, 'col_idx': 2},
   {'text': '(634) |', 'row_idx': 21, 'col_idx': 0},
   {'text': '(631) |', 'row_idx': 21, 'col_idx': 1},
   {'text': '(571) |', 'row_idx': 21, 'col_idx': 2},
   {'text': '2,658 |', 'row_idx': 22, 'col_idx': 0},
   {'text': '3,040 |', 'row_idx': 22, 'col_idx': 1},
   {'text': '3,773 |', 'row_idx': 22, 'col_idx': 2},
   {'text': '529 |', 'row_idx': 23, 'col_idx': 0},
   {'text': '896 |', 'row_idx': 23, 'col_idx': 1},
   {'text': '1,539 |', 'row_idx': 23, 'col_idx': 2},
   {'text': '$2,129 |', 'row_idx': 24, 'col_idx': 0},
   {'text': '$2,144 |', 'row_idx': 24, 'col_idx': 1},
   {'text': '$2,234 |', 'row_idx': 24, 'col_idx': 2},
   {'text': '$7.73 |', 'row_idx': 25, 'col_idx': 0},
   {'text': '$7.08 |', 'row_idx': 25, 'col_idx': 1},
   {'text': '$6.77 |', 'row_idx': 25, 'col_idx': 2},
   {'text': '$7.70 |', 'row_idx': 26, 'col_idx': 0},
   {'text': '$7.06 |', 'row_idx': 26, 'col_idx': 1},
   {'text': '$6.76 |', 'row_idx': 26, 'col_idx': 2}]},
 {'id': 'tab-5_tab-5',
  'title': 'tab-5',
  'cells': [{'text': 'At December 31, |', 'row_idx': 0, 'col_idx': 0},
   {'text': '2018 |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'At December 31, |', 'row_idx': 0, 'col_idx': 2},
   {'text': '2017 (a).', 'row_idx': 0, 'col_idx': 3},
   {'text': '$1,694 |', 'row_idx': 1, 'col_idx': 0},
   {'text': '$1,482 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '2,256 |', 'row_idx': 2, 'col_idx': 0},
   {'text': '2,316 |', 'row_idx': 2, 'col_idx': 1},
   {'text': '1,346 |', 'row_idx': 3, 'col_idx': 0},
   {'text': '1,340 |', 'row_idx': 3, 'col_idx': 1},
   {'text': '985 |', 'row_idx': 4, 'col_idx': 0},
   {'text': '924 |', 'row_idx': 4, 'col_idx': 1},
   {'text': '913 |', 'row_idx': 5, 'col_idx': 0},
   {'text': '1,071 |', 'row_idx': 5, 'col_idx': 1},
   {'text': '7,194 |', 'row_idx': 6, 'col_idx': 0},
   {'text': '7,133 |', 'row_idx': 6, 'col_idx': 1},
   {'text': '31,607 |', 'row_idx': 7, 'col_idx': 0},
   {'text': '28,692 |', 'row_idx': 7, 'col_idx': 1},
   {'text': '7,919 |', 'row_idx': 8, 'col_idx': 0},
   {'text': '6,946 |', 'row_idx': 8, 'col_idx': 1},
   {'text': '39,526 |', 'row_idx': 9, 'col_idx': 0},
   {'text': '35,638 |', 'row_idx': 9, 'col_idx': 1},
   {'text': '(12,760) |', 'row_idx': 10, 'col_idx': 0},

Tentativo 3

In [ ]:
import json

def transform_table(table):
    id = table['id']
    title = id.split('_')[0].lower().replace('_', ' ')
    cells = []

    # Flatten column headers
    flat_headers = []
    for header in table['column_header']:
        flat_headers.extend(header)

    # Check if row headers exist
    has_row_headers = 'row_header' in table and table['row_header']

    # Add dummy header for row headers if they exist
    if has_row_headers:
        cells.append({
            "text": "Header |",
            "row_idx": 0,
            "col_idx": 0
        })
        # Shift other headers
        for col_idx, header in enumerate(flat_headers, start=1):
            cells.append({
                "text": f"{header} |",
                "row_idx": 0,
                "col_idx": col_idx
            })
    else:
        # Add column headers as cells without shift
        for col_idx, header in enumerate(flat_headers):
            cells.append({
                "text": f"{header} |",
                "row_idx": 0,
                "col_idx": col_idx
            })

    # Add data cells
    for row_idx, row_data in enumerate(table['data'], start=1):
        # Add row header as the first column if it exists
        if has_row_headers:
            row_header = ' '.join(table['row_header'][row_idx-1])
            cells.append({
                "text": f"{row_header} |",
                "row_idx": row_idx,
                "col_idx": 0
            })
            # Add data cells with shift
            for col_idx, cell_data in enumerate(row_data, start=1):
                cells.append({
                    "text": f"{cell_data} |",
                    "row_idx": row_idx,
                    "col_idx": col_idx
                })
        else:
            # Add data cells without shift
            for col_idx, cell_data in enumerate(row_data):
                cells.append({
                    "text": f"{cell_data} |",
                    "row_idx": row_idx,
                    "col_idx": col_idx
                })

    # Remove the trailing '|' from the last cell in each row
    max_col = max(cell['col_idx'] for cell in cells)
    for cell in cells:
        if cell['col_idx'] == max_col:
            cell['text'] = cell['text'].rstrip('| ') + '.'

    return {
        "id": f"{title}_{id}",
        "title": title,
        "cells": cells
    }

# Read the JSONL file and transform each table
transformed_tables = []
with open('/content/aitqa_tables.jsonl', 'r') as file:
    for line in file:
        table = json.loads(line)
        transformed_table = transform_table(table)
        transformed_tables.append(transformed_table)

# Write the transformed tables to a new JSONL file
with open('transformed_tables3.jsonl', 'w') as file:
    for table in transformed_tables:
        json.dump(table, file)
        file.write('\n')

In [ ]:
import pandas as pd
import json

json_list = []
with open('/content/transformed_tables3.jsonl', 'r') as file:
    for line in file:
        json_list.append(json.loads(line))

json_list

[{'id': 'tab-0_tab-0',
  'title': 'tab-0',
  'cells': [{'text': 'Year |', 'row_idx': 0, 'col_idx': 0},
   {'text': 'Gallons Consumed (in millions) |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Fuel Expense       (in millions) |', 'row_idx': 0, 'col_idx': 2},
   {'text': 'Average Price Per Gallon |', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Percentage of Total Operating Expense |',
    'row_idx': 0,
    'col_idx': 4},
   {'text': 'Available Seat Miles per Fuel Gallon.',
    'row_idx': 0,
    'col_idx': 5},
   {'text': '2018 |', 'row_idx': 1, 'col_idx': 0},
   {'text': '4,137 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$9,307 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$2.25 |', 'row_idx': 1, 'col_idx': 3},
   {'text': '24% |', 'row_idx': 1, 'col_idx': 4},
   {'text': '67.', 'row_idx': 1, 'col_idx': 5},
   {'text': '2017 |', 'row_idx': 2, 'col_idx': 0},
   {'text': '3,978 |', 'row_idx': 2, 'col_idx': 1},
   {'text': '$6,913 |', 'row_idx': 2, 'col_idx': 2},
   {'text': '$1.74 |', 'row_idx': 2, 'col_idx': 3},
   {'text': '20% |', 'row_idx': 2, 'col_idx': 4},
   {'text': '66.', 'row_idx': 2, 'col_idx': 5},
   {'text': '2016 |', 'row_idx': 3, 'col_idx': 0},
   {'text': '3,904 |', 'row_idx': 3, 'col_idx': 1},
   {'text': '$5,813 |', 'row_idx': 3, 'col_idx': 2},
   {'text': '$1.49 |', 'row_idx': 3, 'col_idx': 3},
   {'text': '18% |', 'row_idx': 3, 'col_idx': 4},
   {'text': '65.', 'row_idx': 3, 'col_idx': 5}]},
 {'id': 'tab-1_tab-1',
  'title': 'tab-1',
  'cells': [{'text': 'Header |', 'row_idx': 0, 'col_idx': 0},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 1},
   {'text': '2018 |', 'row_idx': 0, 'col_idx': 2},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 3},
   {'text': '2017 (a) |', 'row_idx': 0, 'col_idx': 4},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 5},
   {'text': '2016 (a) |', 'row_idx': 0, 'col_idx': 6},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 7},
   {'text': '2015 |', 'row_idx': 0, 'col_idx': 8},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 9},
   {'text': '2014.', 'row_idx': 0, 'col_idx': 10},
   {'text': 'Consolidated (b) Passengers (thousands) (c) |',
    'row_idx': 1,
    'col_idx': 0},
   {'text': '158,330 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '148,067 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '143,177 |', 'row_idx': 1, 'col_idx': 3},
   {'text': '140,369 |', 'row_idx': 1, 'col_idx': 4},
   {'text': '138,029 |', 'row_idx': 1, 'col_idx': 5},
   {'text': 'Consolidated (b) Revenue passenger miles ("RPMs") (millions) (d) |',
    'row_idx': 2,
    'col_idx': 0},
   {'text': '230,155 |', 'row_idx': 2, 'col_idx': 1},
   {'text': '216,261 |', 'row_idx': 2, 'col_idx': 2},
   {'text': '210,309 |', 'row_idx': 2, 'col_idx': 3},
   {'text': '208,611 |', 'row_idx': 2, 'col_idx': 4},
   {'text': '205,559 |', 'row_idx': 2, 'col_idx': 5},
   {'text': 'Consolidated (b) Available seat miles ("ASMs") (millions) (e) |',
    'row_idx': 3,
    'col_idx': 0},
   {'text': '275,262 |', 'row_idx': 3, 'col_idx': 1},
   {'text': '262,386 |', 'row_idx': 3, 'col_idx': 2},
   {'text': '253,590 |', 'row_idx': 3, 'col_idx': 3},
   {'text': '250,003 |', 'row_idx': 3, 'col_idx': 4},
   {'text': '246,021 |', 'row_idx': 3, 'col_idx': 5},
   {'text': 'Consolidated (b) Cargo revenue ton miles (millions) (f) |',
    'row_idx': 4,
    'col_idx': 0},
   {'text': '3,425 |', 'row_idx': 4, 'col_idx': 1},
   {'text': '3,316 |', 'row_idx': 4, 'col_idx': 2},
   {'text': '2,805 |', 'row_idx': 4, 'col_idx': 3},
   {'text': '2,614 |', 'row_idx': 4, 'col_idx': 4},
   {'text': '2,487 |', 'row_idx': 4, 'col_idx': 5},
   {'text': 'Consolidated (b) Passenger load factor (g) |',
    'row_idx': 5,
    'col_idx': 0},
   {'text': '83.6% |', 'row_idx': 5, 'col_idx': 1},
   {'text': '82.4% |', 'row_idx': 5, 'col_idx': 2},
   {'text': '82.9% |', 'row_idx': 5, 'col_idx': 3},
   {'text': '83.4% |', 'row_idx': 5, 'col_idx': 4},
   {'text': '83.6% |', 'row_idx': 5, 'col_idx': 5},
   {'text': 'Consolidated (b) Passenger revenue per available seat mile ("PRASM") (cents) |',
    'row_idx': 6,
    'col_idx': 0},
   {'text': '13.70 |', 'row_idx': 6, 'col_idx': 1},
   {'text': '13.13 |', 'row_idx': 6, 'col_idx': 2},
   {'text': '13.18 |', 'row_idx': 6, 'col_idx': 3},
   {'text': '13.11 |', 'row_idx': 6, 'col_idx': 4},
   {'text': '13.72 |', 'row_idx': 6, 'col_idx': 5},
   {'text': 'Consolidated (b) Total revenue per available seat mile ("TRASM") (cents) |',
    'row_idx': 7,
    'col_idx': 0},
   {'text': '15.00 |', 'row_idx': 7, 'col_idx': 1},
   {'text': '14.40 |', 'row_idx': 7, 'col_idx': 2},
   {'text': '14.42 |', 'row_idx': 7, 'col_idx': 3},
   {'text': '15.15 |', 'row_idx': 7, 'col_idx': 4},
   {'text': '15.81 |', 'row_idx': 7, 'col_idx': 5},
   {'text': 'Consolidated (b) Average yield per revenue passenger mile ("Yield") (cents) (h) |',
    'row_idx': 8,
    'col_idx': 0},
   {'text': '16.38 |', 'row_idx': 8, 'col_idx': 1},
   {'text': '15.93 |', 'row_idx': 8, 'col_idx': 2},
   {'text': '15.90 |', 'row_idx': 8, 'col_idx': 3},
   {'text': '15.72 |', 'row_idx': 8, 'col_idx': 4},
   {'text': '16.42 |', 'row_idx': 8, 'col_idx': 5},
   {'text': 'Consolidated (b) Cost per available seat mile ("CASM") (cents) |',
    'row_idx': 9,
    'col_idx': 0},
   {'text': '13.81 |', 'row_idx': 9, 'col_idx': 1},
   {'text': '13.00 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '12.70 |', 'row_idx': 9, 'col_idx': 3},
   {'text': '13.08 |', 'row_idx': 9, 'col_idx': 4},
   {'text': '14.85 |', 'row_idx': 9, 'col_idx': 5},
   {'text': 'Consolidated (b) Average price per gallon of fuel, including fuel taxes |',
    'row_idx': 10,
    'col_idx': 0},
   {'text': '$2.25 |', 'row_idx': 10, 'col_idx': 1},
   {'text': '$1.74 |', 'row_idx': 10, 'col_idx': 2},
   {'text': '$1.49 |', 'row_idx': 10, 'col_idx': 3},
   {'text': '$1.94 |', 'row_idx': 10, 'col_idx': 4},
   {'text': '$2.99 |', 'row_idx': 10, 'col_idx': 5},
   {'text': 'Consolidated (b) Fuel gallons consumed (millions) |',
    'row_idx': 11,
    'col_idx': 0},
   {'text': '4,137 |', 'row_idx': 11, 'col_idx': 1},
   {'text': '3,978 |', 'row_idx': 11, 'col_idx': 2},
   {'text': '3,904 |', 'row_idx': 11, 'col_idx': 3},
   {'text': '3,886 |', 'row_idx': 11, 'col_idx': 4},
   {'text': '3,905 |', 'row_idx': 11, 'col_idx': 5},
   {'text': 'Consolidated (b) Average stage length (miles) (i) |',
    'row_idx': 12,
    'col_idx': 0},
   {'text': '1,446 |', 'row_idx': 12, 'col_idx': 1},
   {'text': '1,460 |', 'row_idx': 12, 'col_idx': 2},
   {'text': '1,473 |', 'row_idx': 12, 'col_idx': 3},
   {'text': '1,487 |', 'row_idx': 12, 'col_idx': 4},
   {'text': '1,480 |', 'row_idx': 12, 'col_idx': 5},
   {'text': 'Consolidated (b) Average daily utilization of each mainline aircraft (hours:minutes) (j) |',
    'row_idx': 13,
    'col_idx': 0},
   {'text': '10:45 |', 'row_idx': 13, 'col_idx': 1},
   {'text': '10:27 |', 'row_idx': 13, 'col_idx': 2},
   {'text': '10:06 |', 'row_idx': 13, 'col_idx': 3},
   {'text': '10:24 |', 'row_idx': 13, 'col_idx': 4},
   {'text': '10:26 |', 'row_idx': 13, 'col_idx': 5}]},
 {'id': 'tab-2_tab-2',
  'title': 'tab-2',
  'cells': [{'text': 'Header |', 'row_idx': 0, 'col_idx': 0},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 1},
   {'text': 'Domestic |', 'row_idx': 0, 'col_idx': 2},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 3},
   {'text': 'Atlantic |', 'row_idx': 0, 'col_idx': 4},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 5},
   {'text': 'Pacific |', 'row_idx': 0, 'col_idx': 6},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 7},
   {'text': 'Latin |', 'row_idx': 0, 'col_idx': 8},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 9},
   {'text': 'Total |', 'row_idx': 0, 'col_idx': 10},
   {'text': ' |', 'row_idx': 0, 'col_idx': 11},
   {'text': 'Increase (decrease) from 2017 (a): |',
    'row_idx': 0,
    'col_idx': 12},
   {'text': ' |', 'row_idx': 0, 'col_idx': 13},
   {'text': 'Domestic |', 'row_idx': 0, 'col_idx': 14},
   {'text': 'Atlantic.', 'row_idx': 0, 'col_idx': 15},
   {'text': 'Passenger revenue (in millions) |', 'row_idx': 1, 'col_idx': 0},
   {'text': '$2,340 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$688 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$185 |', 'row_idx': 1, 'col_idx': 3},
   {'text': '$33 |', 'row_idx': 1, 'col_idx': 4},
   {'text': '$3,246 |', 'row_idx': 1, 'col_idx': 5},
   {'text': ' |', 'row_idx': 1, 'col_idx': 6},
   {'text': 'Passenger revenue |', 'row_idx': 2, 'col_idx': 0},
   {'text': '11.1% |', 'row_idx': 2, 'col_idx': 1},
   {'text': '11.7 % |', 'row_idx': 2, 'col_idx': 2},
   {'text': '4.3 % |', 'row_idx': 2, 'col_idx': 3},
   {'text': '1.0 % |', 'row_idx': 2, 'col_idx': 4},
   {'text': '9.4% |', 'row_idx': 2, 'col_idx': 5},
   {'text': ' |', 'row_idx': 2, 'col_idx': 6},
   {'text': 'Average fare per passenger |', 'row_idx': 3, 'col_idx': 0},
   {'text': '2.8% |', 'row_idx': 3, 'col_idx': 1},
   {'text': '0.2 % |', 'row_idx': 3, 'col_idx': 2},
   {'text': '8.5 % |', 'row_idx': 3, 'col_idx': 3},
   {'text': '2.5 % |', 'row_idx': 3, 'col_idx': 4},
   {'text': '2.3% |', 'row_idx': 3, 'col_idx': 5},
   {'text': ' |', 'row_idx': 3, 'col_idx': 6},
   {'text': 'Yield |', 'row_idx': 4, 'col_idx': 0},
   {'text': '3.8% |', 'row_idx': 4, 'col_idx': 1},
   {'text': '(0.4)% |', 'row_idx': 4, 'col_idx': 2},
   {'text': '2.7 % |', 'row_idx': 4, 'col_idx': 3},
   {'text': '(0.3)% |', 'row_idx': 4, 'col_idx': 4},
   {'text': '2.8% |', 'row_idx': 4, 'col_idx': 5},
   {'text': ' |', 'row_idx': 4, 'col_idx': 6},
   {'text': 'PRASM |', 'row_idx': 5, 'col_idx': 0},
   {'text': '4.1% |', 'row_idx': 5, 'col_idx': 1},
   {'text': '6.3 % |', 'row_idx': 5, 'col_idx': 2},
   {'text': '3.0 % |', 'row_idx': 5, 'col_idx': 3},
   {'text': '0.8 % |', 'row_idx': 5, 'col_idx': 4},
   {'text': '4.3% |', 'row_idx': 5, 'col_idx': 5},
   {'text': ' |', 'row_idx': 5, 'col_idx': 6},
   {'text': 'Passengers |', 'row_idx': 6, 'col_idx': 0},
   {'text': '8.1% |', 'row_idx': 6, 'col_idx': 1},
   {'text': '11.5 % |', 'row_idx': 6, 'col_idx': 2},
   {'text': '(3.9)% |', 'row_idx': 6, 'col_idx': 3},
   {'text': '(1.4)% |', 'row_idx': 6, 'col_idx': 4},
   {'text': '6.9% |', 'row_idx': 6, 'col_idx': 5},
   {'text': ' |', 'row_idx': 6, 'col_idx': 6},
   {'text': 'RPMs (traffic) |', 'row_idx': 7, 'col_idx': 0},
   {'text': '7.0% |', 'row_idx': 7, 'col_idx': 1},
   {'text': '12.1 % |', 'row_idx': 7, 'col_idx': 2},
   {'text': '1.5 % |', 'row_idx': 7, 'col_idx': 3},
   {'text': '1.3 % |', 'row_idx': 7, 'col_idx': 4},
   {'text': '6.4% |', 'row_idx': 7, 'col_idx': 5},
   {'text': ' |', 'row_idx': 7, 'col_idx': 6},
   {'text': 'ASMs (capacity) |', 'row_idx': 8, 'col_idx': 0},
   {'text': '6.7% |', 'row_idx': 8, 'col_idx': 1},
   {'text': '5.1 % |', 'row_idx': 8, 'col_idx': 2},
   {'text': '1.3 % |', 'row_idx': 8, 'col_idx': 3},
   {'text': '0.3 % |', 'row_idx': 8, 'col_idx': 4},
   {'text': '4.9% |', 'row_idx': 8, 'col_idx': 5},
   {'text': ' |', 'row_idx': 8, 'col_idx': 6},
   {'text': 'Passenger load factor (points) |', 'row_idx': 9, 'col_idx': 0},
   {'text': '0.2 |', 'row_idx': 9, 'col_idx': 1},
   {'text': '5.1 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '0.2 |', 'row_idx': 9, 'col_idx': 3},
   {'text': '0.8 |', 'row_idx': 9, 'col_idx': 4},
   {'text': '1.2 |', 'row_idx': 9, 'col_idx': 5},
   {'text': ' |', 'row_idx': 9, 'col_idx': 6},
   {'text': '11 |', 'row_idx': 10, 'col_idx': 0},
   {'text': ' |', 'row_idx': 10, 'col_idx': 1},
   {'text': ' |', 'row_idx': 10, 'col_idx': 2},
   {'text': ' |', 'row_idx': 10, 'col_idx': 3},
   {'text': ' |', 'row_idx': 10, 'col_idx': 4},
   {'text': ' |', 'row_idx': 10, 'col_idx': 5},
   {'text': '(a) See Part II, Item 6, Selected Financial Data, of this report for the definition of these statistics. |',
    'row_idx': 10,
    'col_idx': 6}]},
 {'id': 'tab-3_tab-3',
  'title': 'tab-3',
  'cells': [{'text': 'Header |', 'row_idx': 0, 'col_idx': 0},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 1},
   {'text': 'Domestic |', 'row_idx': 0, 'col_idx': 2},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 3},
   {'text': 'Atlantic |', 'row_idx': 0, 'col_idx': 4},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 5},
   {'text': 'Pacific |', 'row_idx': 0, 'col_idx': 6},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 7},
   {'text': 'Latin |', 'row_idx': 0, 'col_idx': 8},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 9},
   {'text': 'Total |', 'row_idx': 0, 'col_idx': 10},
   {'text': ' |', 'row_idx': 0, 'col_idx': 11},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): |',
    'row_idx': 0,
    'col_idx': 12},
   {'text': ' |', 'row_idx': 0, 'col_idx': 13},
   {'text': 'Domestic |', 'row_idx': 0, 'col_idx': 14},
   {'text': 'Atlantic |', 'row_idx': 0, 'col_idx': 15},
   {'text': 'Pacific |', 'row_idx': 0, 'col_idx': 16},
   {'text': 'Latin |', 'row_idx': 0, 'col_idx': 17},
   {'text': 'Total.', 'row_idx': 0, 'col_idx': 18},
   {'text': 'Passenger revenue (in millions) |', 'row_idx': 1, 'col_idx': 0},
   {'text': '$885 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$117 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$(144) |', 'row_idx': 1, 'col_idx': 3},
   {'text': '$173 |', 'row_idx': 1, 'col_idx': 4},
   {'text': '$1,031 |', 'row_idx': 1, 'col_idx': 5},
   {'text': ' |', 'row_idx': 1, 'col_idx': 6},
   {'text': 'Passenger revenue |', 'row_idx': 2, 'col_idx': 0},
   {'text': '4.4 % |', 'row_idx': 2, 'col_idx': 1},
   {'text': '2.0% |', 'row_idx': 2, 'col_idx': 2},
   {'text': '(3.2)% |', 'row_idx': 2, 'col_idx': 3},
   {'text': '5.8% |', 'row_idx': 2, 'col_idx': 4},
   {'text': '3.1 % |', 'row_idx': 2, 'col_idx': 5},
   {'text': ' |', 'row_idx': 2, 'col_idx': 6},
   {'text': 'Average fare per passenger |', 'row_idx': 3, 'col_idx': 0},
   {'text': '0.2 % |', 'row_idx': 3, 'col_idx': 1},
   {'text': '1.5% |', 'row_idx': 3, 'col_idx': 2},
   {'text': '(0.1)% |', 'row_idx': 3, 'col_idx': 3},
   {'text': '4.0% |', 'row_idx': 3, 'col_idx': 4},
   {'text': '(0.3)% |', 'row_idx': 3, 'col_idx': 5},
   {'text': ' |', 'row_idx': 3, 'col_idx': 6},
   {'text': 'Yield |', 'row_idx': 4, 'col_idx': 0},
   {'text': '(0.3)% |', 'row_idx': 4, 'col_idx': 1},
   {'text': '1.1% |', 'row_idx': 4, 'col_idx': 2},
   {'text': '(2.4)% |', 'row_idx': 4, 'col_idx': 3},
   {'text': '4.1% |', 'row_idx': 4, 'col_idx': 4},
   {'text': '0.2 % |', 'row_idx': 4, 'col_idx': 5},
   {'text': ' |', 'row_idx': 4, 'col_idx': 6},
   {'text': 'PRASM |', 'row_idx': 5, 'col_idx': 0},
   {'text': '(0.5)% |', 'row_idx': 5, 'col_idx': 1},
   {'text': '1.6% |', 'row_idx': 5, 'col_idx': 2},
   {'text': '(6.0)% |', 'row_idx': 5, 'col_idx': 3},
   {'text': '3.3% |', 'row_idx': 5, 'col_idx': 4},
   {'text': '(0.4)% |', 'row_idx': 5, 'col_idx': 5},
   {'text': ' |', 'row_idx': 5, 'col_idx': 6},
   {'text': 'Passengers |', 'row_idx': 6, 'col_idx': 0},
   {'text': '4.2 % |', 'row_idx': 6, 'col_idx': 1},
   {'text': '0.5% |', 'row_idx': 6, 'col_idx': 2},
   {'text': '(3.1)% |', 'row_idx': 6, 'col_idx': 3},
   {'text': '1.7% |', 'row_idx': 6, 'col_idx': 4},
   {'text': '3.4 % |', 'row_idx': 6, 'col_idx': 5},
   {'text': ' |', 'row_idx': 6, 'col_idx': 6},
   {'text': 'RPMs (traffic) |', 'row_idx': 7, 'col_idx': 0},
   {'text': '4.7 % |', 'row_idx': 7, 'col_idx': 1},
   {'text': '0.9% |', 'row_idx': 7, 'col_idx': 2},
   {'text': '(0.9)% |', 'row_idx': 7, 'col_idx': 3},
   {'text': '1.6% |', 'row_idx': 7, 'col_idx': 4},
   {'text': '2.8 % |', 'row_idx': 7, 'col_idx': 5},
   {'text': ' |', 'row_idx': 7, 'col_idx': 6},
   {'text': 'ASMs (capacity) |', 'row_idx': 8, 'col_idx': 0},
   {'text': '4.9 % |', 'row_idx': 8, 'col_idx': 1},
   {'text': '0.4% |', 'row_idx': 8, 'col_idx': 2},
   {'text': '2.9 % |', 'row_idx': 8, 'col_idx': 3},
   {'text': '2.4% |', 'row_idx': 8, 'col_idx': 4},
   {'text': '3.5 % |', 'row_idx': 8, 'col_idx': 5},
   {'text': ' |', 'row_idx': 8, 'col_idx': 6},
   {'text': 'Passenger load factor (points) |', 'row_idx': 9, 'col_idx': 0},
   {'text': '(0.2) |', 'row_idx': 9, 'col_idx': 1},
   {'text': '0.4 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '(3.0) |', 'row_idx': 9, 'col_idx': 3},
   {'text': '(0.7) |', 'row_idx': 9, 'col_idx': 4},
   {'text': '(0.5) |', 'row_idx': 9, 'col_idx': 5},
   {'text': ' |', 'row_idx': 9, 'col_idx': 6},
   {'text': '11 |', 'row_idx': 10, 'col_idx': 0},
   {'text': ' |', 'row_idx': 10, 'col_idx': 1},
   {'text': ' |', 'row_idx': 10, 'col_idx': 2},
   {'text': ' |', 'row_idx': 10, 'col_idx': 3},
   {'text': ' |', 'row_idx': 10, 'col_idx': 4},
   {'text': ' |', 'row_idx': 10, 'col_idx': 5},
   {'text': '(a) See Part II, Item 6, Selected Financial Data, of this report for the definition of these statistics. |',
    'row_idx': 10,
    'col_idx': 6}]},
 {'id': 'tab-4_tab-4',
  'title': 'tab-4',
  'cells': [{'text': 'Header |', 'row_idx': 0, 'col_idx': 0},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 1},
   {'text': '2018 |', 'row_idx': 0, 'col_idx': 2},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 3},
   {'text': '2017 (a) |', 'row_idx': 0, 'col_idx': 4},
   {'text': 'Year Ended December 31, |', 'row_idx': 0, 'col_idx': 5},
   {'text': '2016 (a).', 'row_idx': 0, 'col_idx': 6},
   {'text': 'Operating revenue: Passenger revenue |',
    'row_idx': 1,
    'col_idx': 0},
   {'text': '$37,706 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$34,460 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$33,429 |', 'row_idx': 1, 'col_idx': 3},
   {'text': 'Operating revenue: Cargo |', 'row_idx': 2, 'col_idx': 0},
   {'text': '1,237 |', 'row_idx': 2, 'col_idx': 1},
   {'text': '1,114 |', 'row_idx': 2, 'col_idx': 2},
   {'text': '934 |', 'row_idx': 2, 'col_idx': 3},
   {'text': 'Operating revenue: Other operating revenue |',
    'row_idx': 3,
    'col_idx': 0},
   {'text': '2,360 |', 'row_idx': 3, 'col_idx': 1},
   {'text': '2,210 |', 'row_idx': 3, 'col_idx': 2},
   {'text': '2,195 |', 'row_idx': 3, 'col_idx': 3},
   {'text': 'Operating revenue: Total operating revenue |',
    'row_idx': 4,
    'col_idx': 0},
   {'text': '41,303 |', 'row_idx': 4, 'col_idx': 1},
   {'text': '37,784 |', 'row_idx': 4, 'col_idx': 2},
   {'text': '36,558 |', 'row_idx': 4, 'col_idx': 3},
   {'text': 'Operating expense: Salaries and related costs |',
    'row_idx': 5,
    'col_idx': 0},
   {'text': '11,458 |', 'row_idx': 5, 'col_idx': 1},
   {'text': '10,941 |', 'row_idx': 5, 'col_idx': 2},
   {'text': '10,176 |', 'row_idx': 5, 'col_idx': 3},
   {'text': 'Operating expense: Aircraft fuel |', 'row_idx': 6, 'col_idx': 0},
   {'text': '9,307 |', 'row_idx': 6, 'col_idx': 1},
   {'text': '6,913 |', 'row_idx': 6, 'col_idx': 2},
   {'text': '5,813 |', 'row_idx': 6, 'col_idx': 3},
   {'text': 'Operating expense: Regional capacity purchase |',
    'row_idx': 7,
    'col_idx': 0},
   {'text': '2,601 |', 'row_idx': 7, 'col_idx': 1},
   {'text': '2,232 |', 'row_idx': 7, 'col_idx': 2},
   {'text': '2,197 |', 'row_idx': 7, 'col_idx': 3},
   {'text': 'Operating expense: Landing fees and other rent |',
    'row_idx': 8,
    'col_idx': 0},
   {'text': '2,359 |', 'row_idx': 8, 'col_idx': 1},
   {'text': '2,240 |', 'row_idx': 8, 'col_idx': 2},
   {'text': '2,165 |', 'row_idx': 8, 'col_idx': 3},
   {'text': 'Operating expense: Depreciation and amortization |',
    'row_idx': 9,
    'col_idx': 0},
   {'text': '2,240 |', 'row_idx': 9, 'col_idx': 1},
   {'text': '2,149 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '1,977 |', 'row_idx': 9, 'col_idx': 3},
   {'text': 'Operating expense: Aircraft maintenance materials and outside repairs |',
    'row_idx': 10,
    'col_idx': 0},

tentativo 4 - GIUSTO

In [ ]:
import json

def transform_table(table):
    id = table['id']
    title = id.split('_')[0].lower().replace('_', ' ')
    cells = []

    # Flatten and combine column headers
    flat_headers = []
    for header in table['column_header']:
        if len(header) > 1:
            flat_headers.append(' '.join(header))
        else:
            flat_headers.extend(header)

    # Check if row headers exist
    has_row_headers = 'row_header' in table and table['row_header']

    # Add dummy header for row headers if they exist
    if has_row_headers:
        cells.append({
            "text": "Header |",
            "row_idx": 0,
            "col_idx": 0
        })
        # Shift other headers
        for col_idx, header in enumerate(flat_headers, start=1):
            cells.append({
                "text": f"{header} |",
                "row_idx": 0,
                "col_idx": col_idx
            })
    else:
        # Add column headers as cells without shift
        for col_idx, header in enumerate(flat_headers):
            cells.append({
                "text": f"{header} |",
                "row_idx": 0,
                "col_idx": col_idx
            })

    # Add data cells
    for row_idx, row_data in enumerate(table['data'], start=1):
        # Add row header as the first column if it exists
        if has_row_headers:
            row_header = ' '.join(table['row_header'][row_idx-1])
            cells.append({
                "text": f"{row_header} |",
                "row_idx": row_idx,
                "col_idx": 0
            })
            # Add data cells with shift
            for col_idx, cell_data in enumerate(row_data, start=1):
                cells.append({
                    "text": f"{cell_data} |",
                    "row_idx": row_idx,
                    "col_idx": col_idx
                })
        else:
            # Add data cells without shift
            for col_idx, cell_data in enumerate(row_data):
                cells.append({
                    "text": f"{cell_data} |",
                    "row_idx": row_idx,
                    "col_idx": col_idx
                })

    # Remove the trailing '|' from the last cell in each row
    max_col = max(cell['col_idx'] for cell in cells)
    for cell in cells:
        if cell['col_idx'] == max_col:
            cell['text'] = cell['text'].rstrip('| ') + '.'

    return {
        "id": f"{title}_{id}",
        "title": title,
        "cells": cells
    }

# Read the JSONL file and transform each table
transformed_tables = []
with open('/content/aitqa_tables.jsonl', 'r') as file:
    for line in file:
        table = json.loads(line)
        transformed_table = transform_table(table)
        transformed_tables.append(transformed_table)

# Write the transformed tables to a new JSONL file
with open('transformed_tables4.jsonl', 'w') as file:
    for table in transformed_tables:
        json.dump(table, file)
        file.write('\n')

In [ ]:
import pandas as pd
import json

json_list = []
with open('/content/transformed_tables4.jsonl', 'r') as file:
    for line in file:
        json_list.append(json.loads(line))

json_list

[{'id': 'tab-0_tab-0',
  'title': 'tab-0',
  'cells': [{'text': 'Year |', 'row_idx': 0, 'col_idx': 0},
   {'text': 'Gallons Consumed (in millions) |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Fuel Expense       (in millions) |', 'row_idx': 0, 'col_idx': 2},
   {'text': 'Average Price Per Gallon |', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Percentage of Total Operating Expense |',
    'row_idx': 0,
    'col_idx': 4},
   {'text': 'Available Seat Miles per Fuel Gallon.',
    'row_idx': 0,
    'col_idx': 5},
   {'text': '2018 |', 'row_idx': 1, 'col_idx': 0},
   {'text': '4,137 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$9,307 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$2.25 |', 'row_idx': 1, 'col_idx': 3},
   {'text': '24% |', 'row_idx': 1, 'col_idx': 4},
   {'text': '67.', 'row_idx': 1, 'col_idx': 5},
   {'text': '2017 |', 'row_idx': 2, 'col_idx': 0},
   {'text': '3,978 |', 'row_idx': 2, 'col_idx': 1},
   {'text': '$6,913 |', 'row_idx': 2, 'col_idx': 2},
   {'text': '$1.74 |', 'row_idx': 2, 'col_idx': 3},
   {'text': '20% |', 'row_idx': 2, 'col_idx': 4},
   {'text': '66.', 'row_idx': 2, 'col_idx': 5},
   {'text': '2016 |', 'row_idx': 3, 'col_idx': 0},
   {'text': '3,904 |', 'row_idx': 3, 'col_idx': 1},
   {'text': '$5,813 |', 'row_idx': 3, 'col_idx': 2},
   {'text': '$1.49 |', 'row_idx': 3, 'col_idx': 3},
   {'text': '18% |', 'row_idx': 3, 'col_idx': 4},
   {'text': '65.', 'row_idx': 3, 'col_idx': 5}]},
 {'id': 'tab-1_tab-1',
  'title': 'tab-1',
  'cells': [{'text': 'Header |', 'row_idx': 0, 'col_idx': 0},
   {'text': 'Year Ended December 31, 2018 |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Year Ended December 31, 2017 (a) |', 'row_idx': 0, 'col_idx': 2},
   {'text': 'Year Ended December 31, 2016 (a) |', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Year Ended December 31, 2015 |', 'row_idx': 0, 'col_idx': 4},
   {'text': 'Year Ended December 31, 2014.', 'row_idx': 0, 'col_idx': 5},
   {'text': 'Consolidated (b) Passengers (thousands) (c) |',
    'row_idx': 1,
    'col_idx': 0},
   {'text': '158,330 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '148,067 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '143,177 |', 'row_idx': 1, 'col_idx': 3},
   {'text': '140,369 |', 'row_idx': 1, 'col_idx': 4},
   {'text': '138,029.', 'row_idx': 1, 'col_idx': 5},
   {'text': 'Consolidated (b) Revenue passenger miles ("RPMs") (millions) (d) |',
    'row_idx': 2,
    'col_idx': 0},
   {'text': '230,155 |', 'row_idx': 2, 'col_idx': 1},
   {'text': '216,261 |', 'row_idx': 2, 'col_idx': 2},
   {'text': '210,309 |', 'row_idx': 2, 'col_idx': 3},
   {'text': '208,611 |', 'row_idx': 2, 'col_idx': 4},
   {'text': '205,559.', 'row_idx': 2, 'col_idx': 5},
   {'text': 'Consolidated (b) Available seat miles ("ASMs") (millions) (e) |',
    'row_idx': 3,
    'col_idx': 0},
   {'text': '275,262 |', 'row_idx': 3, 'col_idx': 1},
   {'text': '262,386 |', 'row_idx': 3, 'col_idx': 2},
   {'text': '253,590 |', 'row_idx': 3, 'col_idx': 3},
   {'text': '250,003 |', 'row_idx': 3, 'col_idx': 4},
   {'text': '246,021.', 'row_idx': 3, 'col_idx': 5},
   {'text': 'Consolidated (b) Cargo revenue ton miles (millions) (f) |',
    'row_idx': 4,
    'col_idx': 0},
   {'text': '3,425 |', 'row_idx': 4, 'col_idx': 1},
   {'text': '3,316 |', 'row_idx': 4, 'col_idx': 2},
   {'text': '2,805 |', 'row_idx': 4, 'col_idx': 3},
   {'text': '2,614 |', 'row_idx': 4, 'col_idx': 4},
   {'text': '2,487.', 'row_idx': 4, 'col_idx': 5},
   {'text': 'Consolidated (b) Passenger load factor (g) |',
    'row_idx': 5,
    'col_idx': 0},
   {'text': '83.6% |', 'row_idx': 5, 'col_idx': 1},
   {'text': '82.4% |', 'row_idx': 5, 'col_idx': 2},
   {'text': '82.9% |', 'row_idx': 5, 'col_idx': 3},
   {'text': '83.4% |', 'row_idx': 5, 'col_idx': 4},
   {'text': '83.6%.', 'row_idx': 5, 'col_idx': 5},
   {'text': 'Consolidated (b) Passenger revenue per available seat mile ("PRASM") (cents) |',
    'row_idx': 6,
    'col_idx': 0},
   {'text': '13.70 |', 'row_idx': 6, 'col_idx': 1},
   {'text': '13.13 |', 'row_idx': 6, 'col_idx': 2},
   {'text': '13.18 |', 'row_idx': 6, 'col_idx': 3},
   {'text': '13.11 |', 'row_idx': 6, 'col_idx': 4},
   {'text': '13.72.', 'row_idx': 6, 'col_idx': 5},
   {'text': 'Consolidated (b) Total revenue per available seat mile ("TRASM") (cents) |',
    'row_idx': 7,
    'col_idx': 0},
   {'text': '15.00 |', 'row_idx': 7, 'col_idx': 1},
   {'text': '14.40 |', 'row_idx': 7, 'col_idx': 2},
   {'text': '14.42 |', 'row_idx': 7, 'col_idx': 3},
   {'text': '15.15 |', 'row_idx': 7, 'col_idx': 4},
   {'text': '15.81.', 'row_idx': 7, 'col_idx': 5},
   {'text': 'Consolidated (b) Average yield per revenue passenger mile ("Yield") (cents) (h) |',
    'row_idx': 8,
    'col_idx': 0},
   {'text': '16.38 |', 'row_idx': 8, 'col_idx': 1},
   {'text': '15.93 |', 'row_idx': 8, 'col_idx': 2},
   {'text': '15.90 |', 'row_idx': 8, 'col_idx': 3},
   {'text': '15.72 |', 'row_idx': 8, 'col_idx': 4},
   {'text': '16.42.', 'row_idx': 8, 'col_idx': 5},
   {'text': 'Consolidated (b) Cost per available seat mile ("CASM") (cents) |',
    'row_idx': 9,
    'col_idx': 0},
   {'text': '13.81 |', 'row_idx': 9, 'col_idx': 1},
   {'text': '13.00 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '12.70 |', 'row_idx': 9, 'col_idx': 3},
   {'text': '13.08 |', 'row_idx': 9, 'col_idx': 4},
   {'text': '14.85.', 'row_idx': 9, 'col_idx': 5},
   {'text': 'Consolidated (b) Average price per gallon of fuel, including fuel taxes |',
    'row_idx': 10,
    'col_idx': 0},
   {'text': '$2.25 |', 'row_idx': 10, 'col_idx': 1},
   {'text': '$1.74 |', 'row_idx': 10, 'col_idx': 2},
   {'text': '$1.49 |', 'row_idx': 10, 'col_idx': 3},
   {'text': '$1.94 |', 'row_idx': 10, 'col_idx': 4},
   {'text': '$2.99.', 'row_idx': 10, 'col_idx': 5},
   {'text': 'Consolidated (b) Fuel gallons consumed (millions) |',
    'row_idx': 11,
    'col_idx': 0},
   {'text': '4,137 |', 'row_idx': 11, 'col_idx': 1},
   {'text': '3,978 |', 'row_idx': 11, 'col_idx': 2},
   {'text': '3,904 |', 'row_idx': 11, 'col_idx': 3},
   {'text': '3,886 |', 'row_idx': 11, 'col_idx': 4},
   {'text': '3,905.', 'row_idx': 11, 'col_idx': 5},
   {'text': 'Consolidated (b) Average stage length (miles) (i) |',
    'row_idx': 12,
    'col_idx': 0},
   {'text': '1,446 |', 'row_idx': 12, 'col_idx': 1},
   {'text': '1,460 |', 'row_idx': 12, 'col_idx': 2},
   {'text': '1,473 |', 'row_idx': 12, 'col_idx': 3},
   {'text': '1,487 |', 'row_idx': 12, 'col_idx': 4},
   {'text': '1,480.', 'row_idx': 12, 'col_idx': 5},
   {'text': 'Consolidated (b) Average daily utilization of each mainline aircraft (hours:minutes) (j) |',
    'row_idx': 13,
    'col_idx': 0},
   {'text': '10:45 |', 'row_idx': 13, 'col_idx': 1},
   {'text': '10:27 |', 'row_idx': 13, 'col_idx': 2},
   {'text': '10:06 |', 'row_idx': 13, 'col_idx': 3},
   {'text': '10:24 |', 'row_idx': 13, 'col_idx': 4},
   {'text': '10:26.', 'row_idx': 13, 'col_idx': 5}]},
 {'id': 'tab-2_tab-2',
  'title': 'tab-2',
  'cells': [{'text': 'Header |', 'row_idx': 0, 'col_idx': 0},
   {'text': 'Increase (decrease) from 2017 (a): Domestic |',
    'row_idx': 0,
    'col_idx': 1},
   {'text': 'Increase (decrease) from 2017 (a): Atlantic |',
    'row_idx': 0,
    'col_idx': 2},
   {'text': 'Increase (decrease) from 2017 (a): Pacific |',
    'row_idx': 0,
    'col_idx': 3},
   {'text': 'Increase (decrease) from 2017 (a): Latin |',
    'row_idx': 0,
    'col_idx': 4},
   {'text': 'Increase (decrease) from 2017 (a): Total |',
    'row_idx': 0,
    'col_idx': 5},
   {'text': ' Increase (decrease) from 2017 (a):  Domestic Atlantic.',
    'row_idx': 0,
    'col_idx': 6},
   {'text': 'Passenger revenue (in millions) |', 'row_idx': 1, 'col_idx': 0},
   {'text': '$2,340 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$688 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$185 |', 'row_idx': 1, 'col_idx': 3},
   {'text': '$33 |', 'row_idx': 1, 'col_idx': 4},
   {'text': '$3,246 |', 'row_idx': 1, 'col_idx': 5},
   {'text': '.', 'row_idx': 1, 'col_idx': 6},
   {'text': 'Passenger revenue |', 'row_idx': 2, 'col_idx': 0},
   {'text': '11.1% |', 'row_idx': 2, 'col_idx': 1},
   {'text': '11.7 % |', 'row_idx': 2, 'col_idx': 2},
   {'text': '4.3 % |', 'row_idx': 2, 'col_idx': 3},
   {'text': '1.0 % |', 'row_idx': 2, 'col_idx': 4},
   {'text': '9.4% |', 'row_idx': 2, 'col_idx': 5},
   {'text': '.', 'row_idx': 2, 'col_idx': 6},
   {'text': 'Average fare per passenger |', 'row_idx': 3, 'col_idx': 0},
   {'text': '2.8% |', 'row_idx': 3, 'col_idx': 1},
   {'text': '0.2 % |', 'row_idx': 3, 'col_idx': 2},
   {'text': '8.5 % |', 'row_idx': 3, 'col_idx': 3},
   {'text': '2.5 % |', 'row_idx': 3, 'col_idx': 4},
   {'text': '2.3% |', 'row_idx': 3, 'col_idx': 5},
   {'text': '.', 'row_idx': 3, 'col_idx': 6},
   {'text': 'Yield |', 'row_idx': 4, 'col_idx': 0},
   {'text': '3.8% |', 'row_idx': 4, 'col_idx': 1},
   {'text': '(0.4)% |', 'row_idx': 4, 'col_idx': 2},
   {'text': '2.7 % |', 'row_idx': 4, 'col_idx': 3},
   {'text': '(0.3)% |', 'row_idx': 4, 'col_idx': 4},
   {'text': '2.8% |', 'row_idx': 4, 'col_idx': 5},
   {'text': '.', 'row_idx': 4, 'col_idx': 6},
   {'text': 'PRASM |', 'row_idx': 5, 'col_idx': 0},
   {'text': '4.1% |', 'row_idx': 5, 'col_idx': 1},
   {'text': '6.3 % |', 'row_idx': 5, 'col_idx': 2},
   {'text': '3.0 % |', 'row_idx': 5, 'col_idx': 3},
   {'text': '0.8 % |', 'row_idx': 5, 'col_idx': 4},
   {'text': '4.3% |', 'row_idx': 5, 'col_idx': 5},
   {'text': '.', 'row_idx': 5, 'col_idx': 6},
   {'text': 'Passengers |', 'row_idx': 6, 'col_idx': 0},
   {'text': '8.1% |', 'row_idx': 6, 'col_idx': 1},
   {'text': '11.5 % |', 'row_idx': 6, 'col_idx': 2},
   {'text': '(3.9)% |', 'row_idx': 6, 'col_idx': 3},
   {'text': '(1.4)% |', 'row_idx': 6, 'col_idx': 4},
   {'text': '6.9% |', 'row_idx': 6, 'col_idx': 5},
   {'text': '.', 'row_idx': 6, 'col_idx': 6},
   {'text': 'RPMs (traffic) |', 'row_idx': 7, 'col_idx': 0},
   {'text': '7.0% |', 'row_idx': 7, 'col_idx': 1},
   {'text': '12.1 % |', 'row_idx': 7, 'col_idx': 2},
   {'text': '1.5 % |', 'row_idx': 7, 'col_idx': 3},
   {'text': '1.3 % |', 'row_idx': 7, 'col_idx': 4},
   {'text': '6.4% |', 'row_idx': 7, 'col_idx': 5},
   {'text': '.', 'row_idx': 7, 'col_idx': 6},
   {'text': 'ASMs (capacity) |', 'row_idx': 8, 'col_idx': 0},
   {'text': '6.7% |', 'row_idx': 8, 'col_idx': 1},
   {'text': '5.1 % |', 'row_idx': 8, 'col_idx': 2},
   {'text': '1.3 % |', 'row_idx': 8, 'col_idx': 3},
   {'text': '0.3 % |', 'row_idx': 8, 'col_idx': 4},
   {'text': '4.9% |', 'row_idx': 8, 'col_idx': 5},
   {'text': '.', 'row_idx': 8, 'col_idx': 6},
   {'text': 'Passenger load factor (points) |', 'row_idx': 9, 'col_idx': 0},
   {'text': '0.2 |', 'row_idx': 9, 'col_idx': 1},
   {'text': '5.1 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '0.2 |', 'row_idx': 9, 'col_idx': 3},
   {'text': '0.8 |', 'row_idx': 9, 'col_idx': 4},
   {'text': '1.2 |', 'row_idx': 9, 'col_idx': 5},
   {'text': '.', 'row_idx': 9, 'col_idx': 6},
   {'text': '11 |', 'row_idx': 10, 'col_idx': 0},
   {'text': ' |', 'row_idx': 10, 'col_idx': 1},
   {'text': ' |', 'row_idx': 10, 'col_idx': 2},
   {'text': ' |', 'row_idx': 10, 'col_idx': 3},
   {'text': ' |', 'row_idx': 10, 'col_idx': 4},
   {'text': ' |', 'row_idx': 10, 'col_idx': 5},
   {'text': '(a) See Part II, Item 6, Selected Financial Data, of this report for the definition of these statistics..',
    'row_idx': 10,
    'col_idx': 6}]},
 {'id': 'tab-3_tab-3',
  'title': 'tab-3',
  'cells': [{'text': 'Header |', 'row_idx': 0, 'col_idx': 0},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): Domestic |',
    'row_idx': 0,
    'col_idx': 1},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): Atlantic |',
    'row_idx': 0,
    'col_idx': 2},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): Pacific |',
    'row_idx': 0,
    'col_idx': 3},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): Latin |',
    'row_idx': 0,
    'col_idx': 4},
   {'text': 'Increase (decrease) in 2017 from 2016 (a): Total |',
    'row_idx': 0,
    'col_idx': 5},
   {'text': ' Increase (decrease) in 2017 from 2016 (a):  Domestic Atlantic Pacific Latin Total.',
    'row_idx': 0,
    'col_idx': 6},
   {'text': 'Passenger revenue (in millions) |', 'row_idx': 1, 'col_idx': 0},
   {'text': '$885 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$117 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$(144) |', 'row_idx': 1, 'col_idx': 3},
   {'text': '$173 |', 'row_idx': 1, 'col_idx': 4},
   {'text': '$1,031 |', 'row_idx': 1, 'col_idx': 5},
   {'text': '.', 'row_idx': 1, 'col_idx': 6},
   {'text': 'Passenger revenue |', 'row_idx': 2, 'col_idx': 0},
   {'text': '4.4 % |', 'row_idx': 2, 'col_idx': 1},
   {'text': '2.0% |', 'row_idx': 2, 'col_idx': 2},
   {'text': '(3.2)% |', 'row_idx': 2, 'col_idx': 3},
   {'text': '5.8% |', 'row_idx': 2, 'col_idx': 4},
   {'text': '3.1 % |', 'row_idx': 2, 'col_idx': 5},
   {'text': '.', 'row_idx': 2, 'col_idx': 6},
   {'text': 'Average fare per passenger |', 'row_idx': 3, 'col_idx': 0},
   {'text': '0.2 % |', 'row_idx': 3, 'col_idx': 1},
   {'text': '1.5% |', 'row_idx': 3, 'col_idx': 2},
   {'text': '(0.1)% |', 'row_idx': 3, 'col_idx': 3},
   {'text': '4.0% |', 'row_idx': 3, 'col_idx': 4},
   {'text': '(0.3)% |', 'row_idx': 3, 'col_idx': 5},
   {'text': '.', 'row_idx': 3, 'col_idx': 6},
   {'text': 'Yield |', 'row_idx': 4, 'col_idx': 0},
   {'text': '(0.3)% |', 'row_idx': 4, 'col_idx': 1},
   {'text': '1.1% |', 'row_idx': 4, 'col_idx': 2},
   {'text': '(2.4)% |', 'row_idx': 4, 'col_idx': 3},
   {'text': '4.1% |', 'row_idx': 4, 'col_idx': 4},
   {'text': '0.2 % |', 'row_idx': 4, 'col_idx': 5},
   {'text': '.', 'row_idx': 4, 'col_idx': 6},
   {'text': 'PRASM |', 'row_idx': 5, 'col_idx': 0},
   {'text': '(0.5)% |', 'row_idx': 5, 'col_idx': 1},
   {'text': '1.6% |', 'row_idx': 5, 'col_idx': 2},
   {'text': '(6.0)% |', 'row_idx': 5, 'col_idx': 3},
   {'text': '3.3% |', 'row_idx': 5, 'col_idx': 4},
   {'text': '(0.4)% |', 'row_idx': 5, 'col_idx': 5},
   {'text': '.', 'row_idx': 5, 'col_idx': 6},
   {'text': 'Passengers |', 'row_idx': 6, 'col_idx': 0},
   {'text': '4.2 % |', 'row_idx': 6, 'col_idx': 1},
   {'text': '0.5% |', 'row_idx': 6, 'col_idx': 2},
   {'text': '(3.1)% |', 'row_idx': 6, 'col_idx': 3},
   {'text': '1.7% |', 'row_idx': 6, 'col_idx': 4},
   {'text': '3.4 % |', 'row_idx': 6, 'col_idx': 5},
   {'text': '.', 'row_idx': 6, 'col_idx': 6},
   {'text': 'RPMs (traffic) |', 'row_idx': 7, 'col_idx': 0},
   {'text': '4.7 % |', 'row_idx': 7, 'col_idx': 1},
   {'text': '0.9% |', 'row_idx': 7, 'col_idx': 2},
   {'text': '(0.9)% |', 'row_idx': 7, 'col_idx': 3},
   {'text': '1.6% |', 'row_idx': 7, 'col_idx': 4},
   {'text': '2.8 % |', 'row_idx': 7, 'col_idx': 5},
   {'text': '.', 'row_idx': 7, 'col_idx': 6},
   {'text': 'ASMs (capacity) |', 'row_idx': 8, 'col_idx': 0},
   {'text': '4.9 % |', 'row_idx': 8, 'col_idx': 1},
   {'text': '0.4% |', 'row_idx': 8, 'col_idx': 2},
   {'text': '2.9 % |', 'row_idx': 8, 'col_idx': 3},
   {'text': '2.4% |', 'row_idx': 8, 'col_idx': 4},
   {'text': '3.5 % |', 'row_idx': 8, 'col_idx': 5},
   {'text': '.', 'row_idx': 8, 'col_idx': 6},
   {'text': 'Passenger load factor (points) |', 'row_idx': 9, 'col_idx': 0},
   {'text': '(0.2) |', 'row_idx': 9, 'col_idx': 1},
   {'text': '0.4 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '(3.0) |', 'row_idx': 9, 'col_idx': 3},
   {'text': '(0.7) |', 'row_idx': 9, 'col_idx': 4},
   {'text': '(0.5) |', 'row_idx': 9, 'col_idx': 5},
   {'text': '.', 'row_idx': 9, 'col_idx': 6},
   {'text': '11 |', 'row_idx': 10, 'col_idx': 0},
   {'text': ' |', 'row_idx': 10, 'col_idx': 1},
   {'text': ' |', 'row_idx': 10, 'col_idx': 2},
   {'text': ' |', 'row_idx': 10, 'col_idx': 3},
   {'text': ' |', 'row_idx': 10, 'col_idx': 4},
   {'text': ' |', 'row_idx': 10, 'col_idx': 5},
   {'text': '(a) See Part II, Item 6, Selected Financial Data, of this report for the definition of these statistics..',
    'row_idx': 10,
    'col_idx': 6}]},
 {'id': 'tab-4_tab-4',
  'title': 'tab-4',
  'cells': [{'text': 'Header |', 'row_idx': 0, 'col_idx': 0},
   {'text': 'Year Ended December 31, 2018 |', 'row_idx': 0, 'col_idx': 1},
   {'text': 'Year Ended December 31, 2017 (a) |', 'row_idx': 0, 'col_idx': 2},
   {'text': 'Year Ended December 31, 2016 (a).', 'row_idx': 0, 'col_idx': 3},
   {'text': 'Operating revenue: Passenger revenue |',
    'row_idx': 1,
    'col_idx': 0},
   {'text': '$37,706 |', 'row_idx': 1, 'col_idx': 1},
   {'text': '$34,460 |', 'row_idx': 1, 'col_idx': 2},
   {'text': '$33,429.', 'row_idx': 1, 'col_idx': 3},
   {'text': 'Operating revenue: Cargo |', 'row_idx': 2, 'col_idx': 0},
   {'text': '1,237 |', 'row_idx': 2, 'col_idx': 1},
   {'text': '1,114 |', 'row_idx': 2, 'col_idx': 2},
   {'text': '934.', 'row_idx': 2, 'col_idx': 3},
   {'text': 'Operating revenue: Other operating revenue |',
    'row_idx': 3,
    'col_idx': 0},
   {'text': '2,360 |', 'row_idx': 3, 'col_idx': 1},
   {'text': '2,210 |', 'row_idx': 3, 'col_idx': 2},
   {'text': '2,195.', 'row_idx': 3, 'col_idx': 3},
   {'text': 'Operating revenue: Total operating revenue |',
    'row_idx': 4,
    'col_idx': 0},
   {'text': '41,303 |', 'row_idx': 4, 'col_idx': 1},
   {'text': '37,784 |', 'row_idx': 4, 'col_idx': 2},
   {'text': '36,558.', 'row_idx': 4, 'col_idx': 3},
   {'text': 'Operating expense: Salaries and related costs |',
    'row_idx': 5,
    'col_idx': 0},
   {'text': '11,458 |', 'row_idx': 5, 'col_idx': 1},
   {'text': '10,941 |', 'row_idx': 5, 'col_idx': 2},
   {'text': '10,176.', 'row_idx': 5, 'col_idx': 3},
   {'text': 'Operating expense: Aircraft fuel |', 'row_idx': 6, 'col_idx': 0},
   {'text': '9,307 |', 'row_idx': 6, 'col_idx': 1},
   {'text': '6,913 |', 'row_idx': 6, 'col_idx': 2},
   {'text': '5,813.', 'row_idx': 6, 'col_idx': 3},
   {'text': 'Operating expense: Regional capacity purchase |',
    'row_idx': 7,
    'col_idx': 0},
   {'text': '2,601 |', 'row_idx': 7, 'col_idx': 1},
   {'text': '2,232 |', 'row_idx': 7, 'col_idx': 2},
   {'text': '2,197.', 'row_idx': 7, 'col_idx': 3},
   {'text': 'Operating expense: Landing fees and other rent |',
    'row_idx': 8,
    'col_idx': 0},
   {'text': '2,359 |', 'row_idx': 8, 'col_idx': 1},
   {'text': '2,240 |', 'row_idx': 8, 'col_idx': 2},
   {'text': '2,165.', 'row_idx': 8, 'col_idx': 3},
   {'text': 'Operating expense: Depreciation and amortization |',
    'row_idx': 9,
    'col_idx': 0},
   {'text': '2,240 |', 'row_idx': 9, 'col_idx': 1},
   {'text': '2,149 |', 'row_idx': 9, 'col_idx': 2},
   {'text': '1,977.', 'row_idx': 9, 'col_idx': 3},
   {'text': 'Operating expense: Aircraft maintenance materials and outside repairs |',
    'row_idx': 10,
    'col_idx': 0},
   {'text': '1,767 |', 'row_idx': 10, 'col_idx': 1},
   {'text': '1,856 |', 'row_idx': 10, 'col_idx': 2},
   {'text': '1,749.', 'row_idx': 10, 'col_idx': 3},
   {'text': 'Operating expense: Distribution expenses |',
    'row_idx': 11,
    'col_idx': 0},
   {'text': '1,558 |', 'row_idx': 11, 'col_idx': 1},
   {'text': '1,435 |', 'row_idx': 11, 'col_idx': 2},
   {'text': '1,395.', 'row_idx': 11, 'col_idx': 3},
   {'text': 'Operating expense: Aircraft rent |', 'row_idx': 12, 'col_idx': 0},
   {'text': '433 |', 'row_idx': 12, 'col_idx': 1},
   {'text': '621 |', 'row_idx': 12, 'col_idx': 2},
   {'text': '680.', 'row_idx': 12, 'col_idx': 3},
   {'text': 'Operating expense: Special charges |',
    'row_idx': 13,
    'col_idx': 0},
   {'text': '487 |', 'row_idx': 13, 'col_idx': 1},
   {'text': '176 |', 'row_idx': 13, 'col_idx': 2},
   {'text': '745.', 'row_idx': 13, 'col_idx': 3},
   {'text': 'Operating expense: Other operating expenses |',
    'row_idx': 14,
    'col_idx': 0},
   {'text': '5,801 |', 'row_idx': 14, 'col_idx': 1},
   {'text': '5,550 |', 'row_idx': 14, 'col_idx': 2},
   {'text': '5,317.', 'row_idx': 14, 'col_idx': 3},
   {'text': 'Operating expense: Total operating expense |',
    'row_idx': 15,
    'col_idx': 0},
   {'text': '38,011 |', 'row_idx': 15, 'col_idx': 1},
   {'text': '34,113 |', 'row_idx': 15, 'col_idx': 2},
   {'text': '32,214.', 'row_idx': 15, 'col_idx': 3},

Ecco un breve riepilogo di ciò che il codice ora fa:

Legge il file JSONL di input.
Per ogni tabella:
Combina le intestazioni di colonna multi-parte in una singola stringa.
Aggiunge una colonna "Header" se sono presenti intestazioni di riga.
Formatta correttamente le celle, aggiungendo '|' e '.' dove necessario.
Crea una struttura JSON con il nuovo formato richiesto.
Scrive le tabelle trasformate in un nuovo file JSONL.
Se in futuro avrai bisogno di ulteriori modifiche o avrai domande su come utilizzare o estendere questo codice, non esitare a chiedere. Buon lavoro con i tuoi dati!

**SIstemazione del dataset con question:**

In [ ]:
import json

def transform_data(input_file, output_file):
    # Leggi il file di input
    with open(input_file, 'r') as f:
        lines = f.readlines()

    # Apri il file di output in modalità scrittura
    with open(output_file, 'w') as f:
        # Processa ogni riga del file di input
        for line in lines:
            data = json.loads(line)

            # Crea la struttura per ogni singola domanda
            transformed_data = {
                "id": f"{data['id']}",
                "table": {
                    "columns": [],
                    "rows": [],
                    "tableId": data["table_id"],
                    "documentTitle": "",
                    "documentUrl": "",
                    "alternativeDocumentUrls": [],
                    "alternativeTableIds": []
                },
                "questions": [{
                    "id": f"{data['id']}_0",
                    "originalText": data["question"],
                    "answer": {
                        "answerTexts": data["answers"]
                    }
                }]
            }

            # Scrivi la linea trasformata nel file di output
            json.dump(transformed_data, f)
            f.write('\n')  # Aggiungi una nuova linea dopo ogni oggetto JSON


# Uso della funzione
input_file = "/content/aitqa_questions.jsonl"  # Sostituisci con il nome del tuo file di input
output_file = "output.json"  # Sostituisci con il nome desiderato per il file di output
transform_data(input_file, output_file)

**Question con tabel popolato**

In [ ]:
'''
import json

def load_table_info(jsonl_file):
    tables = {}
    with open(jsonl_file, 'r') as f:
        for line in f:
            table = json.loads(line)
            tables[table['id']] = table
    return tables

def transform_data(input_file, table_file, output_file):
    # Carica le informazioni delle tabelle dal file JSONL
    table_info = load_table_info(table_file)

    # Leggi il file di input
    with open(input_file, 'r') as f:
        lines = f.readlines()

    # Apri il file di output in modalità scrittura
    with open(output_file, 'w') as f:
        # Processa ogni riga del file di input
        for line in lines:
            data = json.loads(line)

            # Trova le informazioni della tabella corrispondente
            table_data = table_info.get(f"{data['table_id']}_{data['table_id']}", {})

            # Prepara le colonne e le righe
            cells = table_data.get('cells', [])
            if cells:
                max_col = max(cell['col_idx'] for cell in cells) + 1
                max_row = max(cell['row_idx'] for cell in cells) + 1
            else:
                max_col = max_row = 0

            columns = [{"text": ""} for _ in range(max_col)]
            rows = [{"cells": [{"text": ""} for _ in range(max_col)]} for _ in range(max_row)]

            for cell in cells:
                if cell['row_idx'] == 0:
                    columns[cell['col_idx']] = {"text": cell['text'].strip(' |.')}
                rows[cell['row_idx']]["cells"][cell['col_idx']] = {"text": cell['text'].strip(' |.')}

            # Crea la struttura per ogni singola domanda
            transformed_data = {
                "id": f"dev_{data['id']}_0",
                "table": {
                    "columns": columns,
                    "rows": rows,
                    "tableId": f"{data['table_id']}_{data['table_id']}",
                    "documentTitle": table_data.get('title', ''),
                    "documentUrl": "",
                    "alternativeDocumentUrls": [],
                    "alternativeTableIds": []
                },
                "questions": [{
                    "id": f"dev_{data['id']}_0_0",
                    "originalText": data["question"],
                    "answer": {
                        "answerTexts": data["answers"]
                    }
                }]
            }

            # Scrivi la linea trasformata nel file di output
            json.dump(transformed_data, f)
            f.write('\n')  # Aggiungi una nuova linea dopo ogni oggetto JSON

# Uso della funzione
input_file = "/content/aitqa_questions.jsonl"  # File con le domande
table_file = "/content/transformed_tables4.jsonl"  # File con le informazioni delle tabelle
output_file = "trasformed_question_with_tables.json"  # File di output
transform_data(input_file, table_file, output_file)

In [ ]:
import json

def load_table_info(jsonl_file):
    tables = {}
    with open(jsonl_file, 'r') as f:
        for line in f:
            table = json.loads(line)
            tables[table['id']] = table
    return tables

def transform_data(input_file, table_file, output_file):
    # Carica le informazioni delle tabelle dal file JSONL
    table_info = load_table_info(table_file)

    # Leggi il file di input
    with open(input_file, 'r') as f:
        lines = f.readlines()

    # Apri il file di output in modalità scrittura
    with open(output_file, 'w') as f:
        # Processa ogni riga del file di input
        for line in lines:
            data = json.loads(line)

            # Trova le informazioni della tabella corrispondente
            table_data = table_info.get(f"{data['table_id']}_{data['table_id']}", {})

            # Prepara le colonne e le righe
            cells = table_data.get('cells', [])
            if cells:
                max_col = max(cell['col_idx'] for cell in cells) + 1
                max_row = max(cell['row_idx'] for cell in cells) + 1
            else:
                max_col = max_row = 0

            columns = [{"text": ""} for _ in range(max_col)]
            rows = [{"cells": [{"text": ""} for _ in range(max_col)]} for _ in range(1, max_row)]  # Salta la riga 0

            for cell in cells:
                if cell['row_idx'] == 0:
                    columns[cell['col_idx']] = {"text": cell['text'].strip(' |.')}
                elif cell['row_idx'] > 0:
                    rows[cell['row_idx'] - 1]["cells"][cell['col_idx']] = {"text": cell['text'].strip(' |.')}

            # Crea la struttura per ogni singola domanda
            transformed_data = {
                "id": f"dev_{data['id']}_0",
                "table": {
                    "columns": columns,
                    "rows": rows,
                    "tableId": f"{data['table_id']}_{data['table_id']}",
                    "documentTitle": table_data.get('title', ''),
                    "documentUrl": "",
                    "alternativeDocumentUrls": [],
                    "alternativeTableIds": []
                },
                "questions": [{
                    "id": f"dev_{data['id']}_0_0",
                    "originalText": data["question"],
                    "answer": {
                        "answerTexts": data["answers"]
                    }
                }]
            }

            # Scrivi la linea trasformata nel file di output
            json.dump(transformed_data, f)
            f.write('\n')  # Aggiungi una nuova linea dopo ogni oggetto JSON

# Uso della funzione
input_file = "/content/aitqa_questions.jsonl"  # File con le domande
table_file = "/content/transformed_tables4.jsonl"  # File con le informazioni delle tabelle
output_file = "trasformed_question_with_tables2.json"  # File di output
transform_data(input_file, table_file, output_file)